// ---------------------------------------------------------
// Base de dados de filmes
// ---------------------------------------------------------
const FILMES = [
  // ===== Filmes originais =====
  { titulo: "Interestelar", generos: ["Ficção Científica", "Drama","Ação"], ano: 2014, classificacao: "PG-13", duracao: 169, popularidade: "popular", spoilerSensivel: false, sinopse: "Um grupo de astronautas atravessa um buraco de minhoca em busca de um novo lar para a humanidade." },
  { titulo: "Vingadores: Ultimato", generos: ["Ação", "Ficção Científica", "Aventura"], ano: 2019, classificacao: "PG-13", duracao: 181, popularidade: "popular", spoilerSensivel: false, sinopse: "Os heróis remanescentes se unem para reverter os efeitos de uma destruição em escala universal." },
  { titulo: "Clube da Luta", generos: ["Drama", "Suspense"], ano: 1999, classificacao: "18+", duracao: 139, popularidade: "cult", spoilerSensivel: true, sinopse: "Um homem insone forma, ao lado de um vendedor de sabão carismático, um clube de luta clandestino." },
  { titulo: "Cidade de Deus", generos: ["Drama", "Ação"], ano: 2002, classificacao: "18+", duracao: 130, popularidade: "cult", spoilerSensivel: false, sinopse: "A trajetória de jovens ligados ao crime organizado em uma comunidade do Rio de Janeiro, ao longo de duas décadas." },
  { titulo: "Toy Story", generos: ["Animação", "Aventura", "Comédia"], ano: 1995, classificacao: "PG", duracao: 81, popularidade: "popular", spoilerSensivel: false, sinopse: "Um cowboy de brinquedo vê sua posição ameaçada quando um boneco espacial chega ao quarto de seu dono." },
  { titulo: "Divertida Mente", generos: ["Animação", "Comédia", "Drama"], ano: 2015, classificacao: "PG", duracao: 95, popularidade: "popular", spoilerSensivel: false, sinopse: "Dentro da mente de uma garota de onze anos, cinco emoções disputam o controle de suas reações." },
  { titulo: "Coringa", generos: ["Drama", "Suspense"], ano: 2019, classificacao: "16+", duracao: 122, popularidade: "popular", spoilerSensivel: false, sinopse: "Um comediante fracassado mergulha em uma espiral que o transforma em um dos vilões mais icônicos dos quadrinhos." },
  { titulo: "Parasita", generos: ["Drama", "Suspense", "Comédia"], ano: 2019, classificacao: "16+", duracao: 132, popularidade: "popular", spoilerSensivel: true, sinopse: "Uma família de baixa renda se infiltra, aos poucos, na rotina de uma família rica." },
  { titulo: "A Origem", generos: ["Ficção Científica", "Ação", "Suspense"], ano: 2010, classificacao: "PG-13", duracao: 148, popularidade: "popular", spoilerSensivel: false, sinopse: "Um ladrão especializado em roubar segredos através de sonhos recebe a missão inversa: plantar uma ideia." },
  { titulo: "Pantera Negra", generos: ["Ação", "Ficção Científica", "Aventura"], ano: 2018, classificacao: "PG-13", duracao: 134, popularidade: "popular", spoilerSensivel: false, sinopse: "O novo rei de Wakanda precisa proteger seu povo enquanto enfrenta um rival que ameaça seu trono." },
  { titulo: "O Iluminado", generos: ["Terror", "Suspense"], ano: 1980, classificacao: "16+", duracao: 146, popularidade: "cult", spoilerSensivel: false, sinopse: "Um escritor aceita cuidar de um hotel isolado no inverno e começa a perder o contato com a realidade." },
  { titulo: "Hereditário", generos: ["Terror", "Drama"], ano: 2018, classificacao: "18+", duracao: 127, popularidade: "cult", spoilerSensivel: true, sinopse: "Após a morte da avó, uma família começa a desvendar segredos sombrios escondidos por gerações." },
  { titulo: "Corra!", generos: ["Terror", "Suspense"], ano: 2017, classificacao: "16+", duracao: 104, popularidade: "popular", spoilerSensivel: true, sinopse: "Um rapaz visita a família da namorada pela primeira vez e percebe que algo ali não está certo." },
  { titulo: "A Bruxa", generos: ["Terror", "Drama"], ano: 2015, classificacao: "16+", duracao: 92, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma família de colonos isolada na floresta começa a suspeitar de forças sobrenaturais à espreita." },
  { titulo: "Diário de uma Paixão", generos: ["Romance", "Drama"], ano: 2004, classificacao: "PG-13", duracao: 123, popularidade: "popular", spoilerSensivel: false, sinopse: "A história de um casal separado pela diferença de classe social é relembrada décadas depois." },
  { titulo: "Simplesmente Amor", generos: ["Romance", "Comédia"], ano: 2003, classificacao: "PG-13", duracao: 135, popularidade: "popular", spoilerSensivel: false, sinopse: "Diversas histórias de amor se cruzam em Londres nas semanas que antecedem o Natal." },
  { titulo: "Orgulho e Preconceito", generos: ["Romance", "Drama"], ano: 2005, classificacao: "PG", duracao: 129, popularidade: "cult", spoilerSensivel: false, sinopse: "Numa Inglaterra do século XIX, uma jovem de opiniões fortes revê seus julgamentos sobre um pretendente orgulhoso." },
  { titulo: "500 Dias com Ela", generos: ["Romance", "Comédia", "Drama"], ano: 2009, classificacao: "PG-13", duracao: 95, popularidade: "cult", spoilerSensivel: false, sinopse: "Um relacionamento de pouco mais de um ano é revisitado, fora de ordem, em busca do que deu errado." },
  { titulo: "Superbad", generos: ["Comédia"], ano: 2007, classificacao: "16+", duracao: 113, popularidade: "popular", spoilerSensivel: false, sinopse: "Dois amigos inseparáveis correm contra o tempo para comprar bebida antes de uma festa na véspera da formatura." },
  { titulo: "O Grande Hotel Budapeste", generos: ["Comédia", "Aventura"], ano: 2014, classificacao: "PG-13", duracao: 99, popularidade: "cult", spoilerSensivel: false, sinopse: "O concierge de um hotel de luxo e seu jovem lobista se envolvem no roubo de uma pintura valiosa." },
  { titulo: "Se Beber, Não Case!", generos: ["Comédia"], ano: 2009, classificacao: "16+", duracao: 100, popularidade: "popular", spoilerSensivel: false, sinopse: "Três amigos acordam sem memória do noivo, um dia antes do casamento, em Las Vegas." },
  { titulo: "Curtindo a Vida Adoidado", generos: ["Comédia"], ano: 1986, classificacao: "PG-13", duracao: 103, popularidade: "cult", spoilerSensivel: false, sinopse: "Um estudante decide matar aula e viver um dia inesquecível pela cidade com os melhores amigos." },
  { titulo: "Blade Runner 2049", generos: ["Ficção Científica", "Drama", "Suspense"], ano: 2017, classificacao: "16+", duracao: 164, popularidade: "cult", spoilerSensivel: false, sinopse: "Um replicante encontra um segredo capaz de mergulhar o que resta da sociedade no caos." },
  { titulo: "Matrix", generos: ["Ficção Científica", "Ação"], ano: 1999, classificacao: "14+", duracao: 136, popularidade: "popular", spoilerSensivel: false, sinopse: "Um programador descobre que a realidade que conhece é uma simulação controlada por máquinas." },
  { titulo: "Duna", generos: ["Ficção Científica", "Aventura", "Drama"], ano: 2021, classificacao: "PG-13", duracao: 155, popularidade: "popular", spoilerSensivel: false, sinopse: "O herdeiro de uma casa nobre é levado a um planeta desértico disputado por seu recurso mais precioso." },
  { titulo: "Alien, o Oitavo Passageiro", generos: ["Terror", "Ficção Científica", "Suspense"], ano: 1979, classificacao: "16+", duracao: 117, popularidade: "cult", spoilerSensivel: false, sinopse: "A tripulação de uma nave de carga espacial é caçada, uma a uma, por um organismo desconhecido." },
  { titulo: "Mad Max: Estrada da Fúria", generos: ["Ação", "Aventura", "Ficção Científica"], ano: 2015, classificacao: "16+", duracao: 120, popularidade: "popular", spoilerSensivel: false, sinopse: "Numa perseguição sem fim por um deserto pós-apocalíptico, uma guerreira ajuda um grupo de fugitivas." },
  { titulo: "John Wick", generos: ["Ação", "Suspense"], ano: 2014, classificacao: "16+", duracao: 101, popularidade: "popular", spoilerSensivel: false, sinopse: "Um ex-assassino de aluguel volta à ativa após um ato de violência atingir o que restava de sua vida pacata." },
  { titulo: "Gladiador", generos: ["Ação", "Drama", "Aventura"], ano: 2000, classificacao: "16+", duracao: 155, popularidade: "popular", spoilerSensivel: false, sinopse: "Um general romano traído é reduzido à escravidão e passa a lutar como gladiador em busca de vingança." },
  { titulo: "O Poderoso Chefão", generos: ["Drama", "Suspense"], ano: 1972, classificacao: "16+", duracao: 175, popularidade: "cult", spoilerSensivel: false, sinopse: "O filho mais novo de uma família da máfia é gradualmente arrastado para os negócios do pai." },
  { titulo: "Forrest Gump", generos: ["Drama", "Comédia", "Romance"], ano: 1994, classificacao: "14+", duracao: 142, popularidade: "popular", spoilerSensivel: false, sinopse: "Um homem simples e de bom coração atravessa, quase sem querer, décadas de história dos Estados Unidos." },
  { titulo: "A Vida é Bela", generos: ["Drama", "Comédia"], ano: 1997, classificacao: "PG-13", duracao: 116, popularidade: "cult", spoilerSensivel: false, sinopse: "Um pai usa a imaginação e o humor para proteger o filho pequeno da realidade de um campo de concentração." },
  { titulo: "O Auto da Compadecida", generos: ["Comédia", "Drama", "Fantasia"], ano: 2000, classificacao: "PG-13", duracao: 104, popularidade: "cult", spoilerSensivel: false, sinopse: "Dois amigos do sertão nordestino se metem em confusão atrás de confusão até parar diante do juízo final." },
  { titulo: "Como Treinar Seu Dragão", generos: ["Animação", "Aventura", "Fantasia"], ano: 2010, classificacao: "PG", duracao: 98, popularidade: "popular", spoilerSensivel: false, sinopse: "Um jovem viking cria um laço inesperado com o dragão que deveria caçar." },
  { titulo: "Spider-Man: Através do Aranhaverso", generos: ["Animação", "Ação", "Ficção Científica", "Aventura"], ano: 2023, classificacao: "PG", duracao: 140, popularidade: "popular", spoilerSensivel: false, sinopse: "Um jovem herói descobre um multiverso de versões do Homem-Aranha e enfrenta um dilema sobre seu próprio destino." },
  { titulo: "O Labirinto do Fauno", generos: ["Fantasia", "Drama"], ano: 2006, classificacao: "16+", duracao: 118, popularidade: "cult", spoilerSensivel: false, sinopse: "Numa Espanha marcada pela guerra, uma menina descobre um mundo mágico escondido perto de sua nova casa." },
  { titulo: "O Senhor dos Anéis: A Sociedade do Anel", generos: ["Fantasia", "Aventura"], ano: 2001, classificacao: "PG-13", duracao: 178, popularidade: "popular", spoilerSensivel: false, sinopse: "Um hobbit recebe a missão de destruir um anel capaz de dar poder absoluto a um senhor das trevas." },
  { titulo: "Harry Potter e a Pedra Filosofal", generos: ["Fantasia", "Aventura"], ano: 2001, classificacao: "PG", duracao: 152, popularidade: "popular", spoilerSensivel: false, sinopse: "Um garoto órfão descobre, ao completar onze anos, que é bruxo e foi aceito numa escola de magia." },
  { titulo: "Garota Exemplar", generos: ["Suspense", "Drama"], ano: 2014, classificacao: "16+", duracao: 149, popularidade: "popular", spoilerSensivel: true, sinopse: "O desaparecimento repentino de uma mulher, no dia do aniversário de casamento, expõe rachaduras no seu casamento." },
  { titulo: "O Sexto Sentido", generos: ["Suspense", "Drama", "Terror"], ano: 1999, classificacao: "14+", duracao: 107, popularidade: "cult", spoilerSensivel: true, sinopse: "Um psicólogo infantil tenta ajudar um menino que afirma conseguir ver pessoas mortas." },
  { titulo: "Whiplash: Em Busca da Perfeição", generos: ["Drama", "Suspense"], ano: 2014, classificacao: "14+", duracao: 106, popularidade: "cult", spoilerSensivel: false, sinopse: "Um baterista de jazz é levado ao limite pelos métodos implacáveis de um professor obcecado por excelência." },
  { titulo: "La La Land: Cantando Estações", generos: ["Romance", "Drama", "Comédia"], ano: 2016, classificacao: "PG-13", duracao: 128, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma atriz em início de carreira e um pianista de jazz se apaixonam em Los Angeles enquanto perseguem seus sonhos." },

  // ===== Clássicos (antes de 1990) =====
  { titulo: "Psicose", generos: ["Terror", "Suspense"], ano: 1960, classificacao: "16+", duracao: 109, popularidade: "cult", spoilerSensivel: true, sinopse: "Uma funcionária que foge com dinheiro roubado se hospeda em um motel isolado, administrado por um rapaz peculiar." },
  { titulo: "Casablanca", generos: ["Romance", "Drama"], ano: 1942, classificacao: "PG", duracao: 102, popularidade: "cult", spoilerSensivel: false, sinopse: "Na Segunda Guerra, o dono de um bar no Marrocos reencontra um antigo amor que chega acompanhada de um líder da resistência." },
  { titulo: "E.T.: O Extraterrestre", generos: ["Ficção Científica", "Aventura", "Drama"], ano: 1982, classificacao: "PG", duracao: 115, popularidade: "popular", spoilerSensivel: false, sinopse: "Um menino esconde em casa um alienígena deixado para trás na Terra e tenta ajudá-lo a voltar para o seu lar." },
  { titulo: "De Volta para o Futuro", generos: ["Ficção Científica", "Comédia", "Aventura"], ano: 1985, classificacao: "PG", duracao: 116, popularidade: "popular", spoilerSensivel: false, sinopse: "Um adolescente viaja no tempo em um carro adaptado por um cientista excêntrico e precisa garantir que seus pais se apaixonem." },
  { titulo: "Os Caçadores da Arca Perdida", generos: ["Ação", "Aventura"], ano: 1981, classificacao: "PG-13", duracao: 115, popularidade: "popular", spoilerSensivel: false, sinopse: "Um arqueólogo aventureiro corre contra os nazistas para encontrar uma relíquia lendária de poder incalculável." },
  { titulo: "Star Wars: Uma Nova Esperança", generos: ["Ficção Científica", "Aventura", "Ação"], ano: 1977, classificacao: "PG", duracao: 121, popularidade: "popular", spoilerSensivel: false, sinopse: "Um jovem fazendeiro se junta a rebeldes para enfrentar um império galáctico e sua arma de destruição em massa." },
  { titulo: "Star Wars: O Império Contra-Ataca", generos: ["Ficção Científica", "Aventura", "Ação"], ano: 1980, classificacao: "PG", duracao: 124, popularidade: "popular", spoilerSensivel: true, sinopse: "Enquanto os rebeldes fogem do Império, o jovem Luke busca treinamento com um mestre misterioso." },
  { titulo: "O Exterminador do Futuro", generos: ["Ação", "Ficção Científica", "Suspense"], ano: 1984, classificacao: "16+", duracao: 107, popularidade: "popular", spoilerSensivel: false, sinopse: "Um ciborgue é enviado do futuro para matar a mulher cujo filho liderará a resistência contra as máquinas." },
  { titulo: "Os Caça-Fantasmas", generos: ["Comédia", "Fantasia", "Ficção Científica"], ano: 1984, classificacao: "PG", duracao: 105, popularidade: "popular", spoilerSensivel: false, sinopse: "Três cientistas desempregados abrem um negócio para capturar fantasmas em Nova York." },
  { titulo: "Os Goonies", generos: ["Aventura", "Comédia"], ano: 1985, classificacao: "PG", duracao: 114, popularidade: "popular", spoilerSensivel: false, sinopse: "Um grupo de crianças encontra um mapa do tesouro de um pirata e parte para salvar suas casas da demolição." },
  { titulo: "Tubarão", generos: ["Suspense", "Aventura", "Terror"], ano: 1975, classificacao: "14+", duracao: 124, popularidade: "popular", spoilerSensivel: false, sinopse: "Um xerife, um biólogo marinho e um pescador saem para caçar um tubarão que aterroriza uma cidade litorânea." },
  { titulo: "O Exorcista", generos: ["Terror"], ano: 1973, classificacao: "18+", duracao: 122, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma mãe desesperada pede ajuda a dois padres quando a filha adolescente passa a apresentar comportamentos aterrorizantes." },
  { titulo: "Taxi Driver", generos: ["Drama", "Suspense"], ano: 1976, classificacao: "18+", duracao: 114, popularidade: "cult", spoilerSensivel: false, sinopse: "Um veterano de guerra com insônia trabalha como taxista noturno e vê a solidão e a revolta crescerem dentro de si." },
  { titulo: "Rocky: Um Lutador", generos: ["Drama"], ano: 1976, classificacao: "PG", duracao: 119, popularidade: "popular", spoilerSensivel: false, sinopse: "Um boxeador de segunda linha ganha a chance rara de disputar o título mundial contra o campeão." },
  { titulo: "Blade Runner: O Caçador de Androides", generos: ["Ficção Científica", "Suspense", "Drama"], ano: 1982, classificacao: "16+", duracao: 117, popularidade: "cult", spoilerSensivel: false, sinopse: "Em uma Los Angeles futurista, um policial é chamado de volta à ativa para caçar replicantes fugitivos." },
  { titulo: "Beetlejuice", generos: ["Comédia", "Fantasia", "Terror"], ano: 1988, classificacao: "PG", duracao: 92, popularidade: "cult", spoilerSensivel: false, sinopse: "Um casal de fantasmas recorre a um espírito trambiqueiro para expulsar a nova família que ocupou sua casa." },
  { titulo: "A Princesa Prometida", generos: ["Fantasia", "Aventura", "Romance", "Comédia"], ano: 1987, classificacao: "PG", duracao: 98, popularidade: "cult", spoilerSensivel: false, sinopse: "Um avô lê para o neto a história de um jovem que enfrenta piratas, gigantes e príncipes para resgatar seu grande amor." },
  { titulo: "Poltergeist: O Fenômeno", generos: ["Terror", "Suspense"], ano: 1982, classificacao: "14+", duracao: 114, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma família de subúrbio passa a ser atormentada por presenças sobrenaturais dentro de casa." },
  { titulo: "A Hora do Pesadelo", generos: ["Terror"], ano: 1984, classificacao: "16+", duracao: 91, popularidade: "cult", spoilerSensivel: false, sinopse: "Adolescentes são perseguidos em seus sonhos por um assassino de rosto queimado e luva de lâminas." },
  { titulo: "Halloween: A Noite do Terror", generos: ["Terror", "Suspense"], ano: 1978, classificacao: "16+", duracao: 91, popularidade: "cult", spoilerSensivel: false, sinopse: "Anos depois de um crime brutal, um assassino mascarado foge de um hospital psiquiátrico e volta à sua cidade natal." },
  { titulo: "Branca de Neve e os Sete Anões", generos: ["Animação", "Fantasia", "Aventura"], ano: 1937, classificacao: "PG", duracao: 83, popularidade: "cult", spoilerSensivel: false, sinopse: "Perseguida pela madrasta invejosa, uma princesa encontra abrigo na casa de sete anões na floresta." },
  { titulo: "Dumbo", generos: ["Animação", "Aventura", "Drama"], ano: 1941, classificacao: "PG", duracao: 64, popularidade: "cult", spoilerSensivel: false, sinopse: "Um filhote de elefante, ridicularizado pelas orelhas enormes, descobre que elas podem levá-lo longe." },
  { titulo: "Pinóquio", generos: ["Animação", "Fantasia", "Aventura"], ano: 1940, classificacao: "PG", duracao: 88, popularidade: "cult", spoilerSensivel: false, sinopse: "Um boneco de madeira ganha vida e precisa provar ser corajoso e sincero para se tornar um menino de verdade." },
  { titulo: "Meu Amigo Totoro", generos: ["Animação", "Fantasia", "Aventura"], ano: 1988, classificacao: "PG", duracao: 86, popularidade: "cult", spoilerSensivel: false, sinopse: "Duas irmãs que se mudam para o campo fazem amizade com criaturas mágicas da floresta." },
  { titulo: "A Pequena Sereia", generos: ["Animação", "Fantasia", "Romance", "Aventura"], ano: 1989, classificacao: "PG", duracao: 83, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma jovem sereia faz um pacto perigoso com uma bruxa do mar para conhecer o mundo dos humanos." },
  { titulo: "Monty Python em Busca do Cálice Sagrado", generos: ["Comédia", "Fantasia", "Aventura"], ano: 1975, classificacao: "PG", duracao: 91, popularidade: "cult", spoilerSensivel: false, sinopse: "O Rei Arthur e seus cavaleiros partem em uma jornada absurda pela Inglaterra medieval atrás do Santo Graal." },
  { titulo: "Duro de Matar", generos: ["Ação", "Suspense"], ano: 1988, classificacao: "18+", duracao: 132, popularidade: "popular", spoilerSensivel: false, sinopse: "Um policial de folga enfrenta sozinho um grupo de terroristas que toma um arranha-céu na noite de Natal." },
  { titulo: "O Mágico de Oz", generos: ["Fantasia", "Aventura"], ano: 1939, classificacao: "PG", duracao: 102, popularidade: "cult", spoilerSensivel: false, sinopse: "Levada por um tornado para uma terra mágica, uma menina segue uma estrada amarela em busca do caminho de casa." },
  { titulo: "E o Vento Levou", generos: ["Romance", "Drama"], ano: 1939, classificacao: "PG", duracao: 238, popularidade: "cult", spoilerSensivel: false, sinopse: "Durante a Guerra Civil americana, uma jovem sulista teimosa luta para salvar sua fazenda e conquistar o homem que ama." },
  { titulo: "Dirty Dancing: Ritmo Quente", generos: ["Romance", "Drama"], ano: 1987, classificacao: "PG-13", duracao: 100, popularidade: "popular", spoilerSensivel: false, sinopse: "Em um resort de verão, uma jovem se envolve com o instrutor de dança e aprende a se arriscar." },
  { titulo: "Bonequinha de Luxo", generos: ["Romance", "Comédia", "Drama"], ano: 1961, classificacao: "PG", duracao: 115, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma jovem sofisticada de Nova York se aproxima de seu novo vizinho escritor enquanto esconde seu passado." },
  { titulo: "Cantando na Chuva", generos: ["Comédia", "Romance"], ano: 1952, classificacao: "PG", duracao: 103, popularidade: "cult", spoilerSensivel: false, sinopse: "Astros do cinema mudo precisam se reinventar com a chegada do cinema falado em Hollywood." },
  { titulo: "2001: Uma Odisseia no Espaço", generos: ["Ficção Científica", "Aventura"], ano: 1968, classificacao: "14+", duracao: 149, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma missão espacial rumo a Júpiter é abalada por um computador de bordo que parece ter vontade própria." },
  { titulo: "Apocalypse Now", generos: ["Drama", "Suspense"], ano: 1979, classificacao: "18+", duracao: 147, popularidade: "cult", spoilerSensivel: false, sinopse: "Durante a Guerra do Vietnã, um capitão sobe um rio em uma missão secreta para eliminar um coronel que enlouqueceu na selva." },
  { titulo: "Um Corpo que Cai", generos: ["Suspense", "Romance", "Drama"], ano: 1958, classificacao: "PG", duracao: 128, popularidade: "cult", spoilerSensivel: true, sinopse: "Um ex-policial com medo de altura é contratado para seguir a esposa de um amigo e acaba obcecado por ela." },
  { titulo: "Janela Indiscreta", generos: ["Suspense", "Romance"], ano: 1954, classificacao: "PG", duracao: 112, popularidade: "cult", spoilerSensivel: false, sinopse: "Um fotógrafo preso em casa por uma perna quebrada passa a suspeitar de um crime no prédio em frente." },

  // ===== Modernos (1990 a 2009) =====
  { titulo: "Pulp Fiction: Tempo de Violência", generos: ["Suspense", "Drama", "Comédia"], ano: 1994, classificacao: "18+", duracao: 154, popularidade: "cult", spoilerSensivel: false, sinopse: "Histórias de criminosos, um boxeador e a esposa de um chefão se cruzam em Los Angeles." },
  { titulo: "O Silêncio dos Inocentes", generos: ["Suspense", "Terror", "Drama"], ano: 1991, classificacao: "18+", duracao: 118, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma agente do FBI pede ajuda a um brilhante psiquiatra canibal para capturar outro assassino em série." },
  { titulo: "Titanic", generos: ["Romance", "Drama"], ano: 1997, classificacao: "14+", duracao: 195, popularidade: "popular", spoilerSensivel: false, sinopse: "Um artista pobre e uma jovem da alta sociedade se apaixonam durante a viagem inaugural do famoso transatlântico." },
  { titulo: "Jurassic Park: Parque dos Dinossauros", generos: ["Aventura", "Ficção Científica", "Ação"], ano: 1993, classificacao: "PG-13", duracao: 127, popularidade: "popular", spoilerSensivel: false, sinopse: "Um parque temático com dinossauros recriados em laboratório sai do controle durante uma visita de especialistas." },
  { titulo: "Os Suspeitos", generos: ["Suspense", "Drama"], ano: 1995, classificacao: "16+", duracao: 106, popularidade: "cult", spoilerSensivel: true, sinopse: "Um sobrevivente conta à polícia como cinco criminosos acabaram envolvidos em um massacre num barco." },
  { titulo: "Seven: Os Sete Crimes Capitais", generos: ["Suspense", "Drama", "Terror"], ano: 1995, classificacao: "18+", duracao: 127, popularidade: "cult", spoilerSensivel: true, sinopse: "Dois detetives investigam uma série de assassinatos inspirados nos sete pecados capitais." },
  { titulo: "Central do Brasil", generos: ["Drama"], ano: 1998, classificacao: "14+", duracao: 113, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma ex-professora que escreve cartas na estação do Rio embarca numa viagem pelo sertão com um menino em busca do pai." },
  { titulo: "O Show de Truman", generos: ["Comédia", "Drama", "Ficção Científica"], ano: 1998, classificacao: "PG", duracao: 103, popularidade: "popular", spoilerSensivel: false, sinopse: "Um homem comum começa a desconfiar de que toda a sua vida é transmitida ao vivo para o mundo inteiro." },
  { titulo: "Piratas do Caribe: A Maldição do Pérola Negra", generos: ["Aventura", "Ação", "Fantasia", "Comédia"], ano: 2003, classificacao: "PG-13", duracao: 143, popularidade: "popular", spoilerSensivel: false, sinopse: "Um pirata excêntrico se une a um ferreiro para resgatar uma jovem sequestrada por uma tripulação amaldiçoada." },
  { titulo: "Procurando Nemo", generos: ["Animação", "Aventura", "Comédia"], ano: 2003, classificacao: "PG", duracao: 100, popularidade: "popular", spoilerSensivel: false, sinopse: "Um peixe-palhaço superprotetor atravessa o oceano com a ajuda de uma peixe distraída para reencontrar o filho." },
  { titulo: "Shrek", generos: ["Animação", "Comédia", "Fantasia", "Aventura"], ano: 2001, classificacao: "PG", duracao: 90, popularidade: "popular", spoilerSensivel: false, sinopse: "Um ogro mal-humorado parte para resgatar uma princesa em troca de recuperar o sossego do seu pântano." },
  { titulo: "Monstros S.A.", generos: ["Animação", "Comédia", "Aventura"], ano: 2001, classificacao: "PG", duracao: 92, popularidade: "popular", spoilerSensivel: false, sinopse: "Dois monstros que trabalham assustando crianças se veem em apuros quando uma menina entra no mundo deles." },
  { titulo: "Ratatouille", generos: ["Animação", "Comédia", "Aventura"], ano: 2007, classificacao: "PG", duracao: 111, popularidade: "popular", spoilerSensivel: false, sinopse: "Um rato com talento para a culinária se une a um jovem ajudante de cozinha em um restaurante de Paris." },
  { titulo: "Up: Altas Aventuras", generos: ["Animação", "Aventura", "Comédia", "Drama"], ano: 2009, classificacao: "PG", duracao: 96, popularidade: "popular", spoilerSensivel: false, sinopse: "Um senhor viúvo amarra balões à sua casa e voa rumo à América do Sul, acompanhado de um escoteiro de carona." },
  { titulo: "WALL·E", generos: ["Animação", "Ficção Científica", "Romance", "Aventura"], ano: 2008, classificacao: "PG", duracao: 98, popularidade: "popular", spoilerSensivel: false, sinopse: "Um pequeno robô que limpa o lixo de uma Terra abandonada conhece uma sonda futurista e a segue pelo espaço." },
  { titulo: "A Viagem de Chihiro", generos: ["Animação", "Fantasia", "Aventura"], ano: 2001, classificacao: "PG", duracao: 125, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma menina entra em um mundo de espíritos e precisa trabalhar numa casa de banhos para libertar os pais." },
  { titulo: "O Senhor dos Anéis: O Retorno do Rei", generos: ["Fantasia", "Aventura", "Ação"], ano: 2003, classificacao: "PG-13", duracao: 201, popularidade: "popular", spoilerSensivel: true, sinopse: "A batalha final pelo destino da Terra-média se aproxima enquanto os hobbits chegam perto da Montanha da Perdição." },
  { titulo: "Kill Bill: Volume 1", generos: ["Ação", "Suspense"], ano: 2003, classificacao: "18+", duracao: 111, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma ex-assassina acorda do coma e parte em uma jornada de vingança contra o grupo que tentou matá-la." },
  { titulo: "Cães de Aluguel", generos: ["Suspense", "Drama"], ano: 1992, classificacao: "18+", duracao: 99, popularidade: "cult", spoilerSensivel: false, sinopse: "Depois de um assalto que dá terrivelmente errado, criminosos tentam descobrir quem os traiu." },
  { titulo: "Edward Mãos de Tesoura", generos: ["Fantasia", "Romance", "Drama"], ano: 1990, classificacao: "PG-13", duracao: 105, popularidade: "cult", spoilerSensivel: false, sinopse: "Um jovem artificial com tesouras no lugar das mãos é acolhido por uma família de um bairro colorido." },
  { titulo: "Brilho Eterno de uma Mente sem Lembranças", generos: ["Romance", "Drama", "Ficção Científica"], ano: 2004, classificacao: "16+", duracao: 108, popularidade: "cult", spoilerSensivel: false, sinopse: "Após o fim do namoro, um casal decide apagar as memórias um do outro por meio de um procedimento experimental." },
  { titulo: "O Fabuloso Destino de Amélie Poulain", generos: ["Romance", "Comédia"], ano: 2001, classificacao: "16+", duracao: 122, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma garçonete tímida de Paris decide melhorar a vida das pessoas ao redor, até que o amor bate à sua porta." },
  { titulo: "Meninas Malvadas", generos: ["Comédia"], ano: 2004, classificacao: "PG-13", duracao: 97, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma garota criada na África se vê no meio das regras cruéis do grupo mais popular de uma escola americana." },
  { titulo: "Pânico", generos: ["Terror", "Suspense"], ano: 1996, classificacao: "16+", duracao: 111, popularidade: "popular", spoilerSensivel: true, sinopse: "Uma cidade pequena é aterrorizada por um assassino mascarado que adora filmes de terror." },
  { titulo: "O Chamado", generos: ["Terror", "Suspense"], ano: 2002, classificacao: "14+", duracao: 115, popularidade: "popular", spoilerSensivel: true, sinopse: "Uma jornalista investiga uma fita de vídeo que, segundo a lenda, causa a morte de quem a assiste em sete dias." },
  { titulo: "Os Outros", generos: ["Terror", "Suspense", "Drama"], ano: 2001, classificacao: "14+", duracao: 104, popularidade: "cult", spoilerSensivel: true, sinopse: "Em uma mansão isolada, uma mãe protege os filhos sensíveis à luz e começa a perceber presenças estranhas." },
  { titulo: "Todo Mundo em Pânico", generos: ["Comédia", "Terror"], ano: 2000, classificacao: "16+", duracao: 88, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma paródia de filmes de terror adolescentes em que um assassino persegue um grupo de jovens." },
  { titulo: "A Bruxa de Blair", generos: ["Terror", "Suspense"], ano: 1999, classificacao: "16+", duracao: 81, popularidade: "cult", spoilerSensivel: false, sinopse: "Três estudantes entram em uma floresta para filmar um documentário sobre uma lenda local e se perdem." },
  { titulo: "Atividade Paranormal", generos: ["Terror", "Suspense"], ano: 2007, classificacao: "16+", duracao: 86, popularidade: "popular", spoilerSensivel: false, sinopse: "Um casal instala câmeras em casa para registrar estranhos fenômenos que ocorrem durante a noite." },
  { titulo: "Cloverfield: Monstro", generos: ["Ficção Científica", "Terror", "Ação"], ano: 2008, classificacao: "14+", duracao: 85, popularidade: "popular", spoilerSensivel: false, sinopse: "Durante uma festa em Nova York, uma criatura gigante ataca a cidade e um grupo de amigos tenta sobreviver." },
  { titulo: "Efeito Borboleta", generos: ["Ficção Científica", "Suspense", "Drama"], ano: 2004, classificacao: "16+", duracao: 113, popularidade: "popular", spoilerSensivel: true, sinopse: "Um jovem descobre que pode voltar no tempo para corrigir o passado, mas cada mudança traz consequências inesperadas." },
  { titulo: "Mamma Mia!", generos: ["Comédia", "Romance"], ano: 2008, classificacao: "PG", duracao: 108, popularidade: "popular", spoilerSensivel: false, sinopse: "Prestes a se casar, uma jovem convida três possíveis pais para o casamento numa ilha grega ao som de músicas do ABBA." },
  { titulo: "Um Amor para Recordar", generos: ["Romance", "Drama"], ano: 2002, classificacao: "PG", duracao: 101, popularidade: "popular", spoilerSensivel: false, sinopse: "Um garoto popular se aproxima de uma colega religiosa e discreta e a convivência muda a vida dos dois." },
  { titulo: "Uma Linda Mulher", generos: ["Romance", "Comédia"], ano: 1990, classificacao: "14+", duracao: 119, popularidade: "popular", spoilerSensivel: false, sinopse: "Um empresário contrata uma acompanhante para uma semana de compromissos e os dois se aproximam mais do que esperavam." },
  { titulo: "Tropa de Elite", generos: ["Ação", "Drama", "Suspense"], ano: 2007, classificacao: "16+", duracao: 115, popularidade: "popular", spoilerSensivel: false, sinopse: "Um capitão do BOPE precisa encontrar um sucessor enquanto lidera operações contra o tráfico no Rio de Janeiro." },
  { titulo: "Antes do Amanhecer", generos: ["Romance", "Drama"], ano: 1995, classificacao: "14+", duracao: 101, popularidade: "cult", spoilerSensivel: false, sinopse: "Dois jovens se conhecem num trem e decidem passar uma noite caminhando e conversando por Viena." },
  { titulo: "Esqueceram de Mim", generos: ["Comédia", "Aventura"], ano: 1990, classificacao: "PG", duracao: 103, popularidade: "popular", spoilerSensivel: false, sinopse: "Um garoto esquecido em casa durante o Natal precisa defender a casa de dois ladrões atrapalhados." },
  { titulo: "Missão: Impossível", generos: ["Ação", "Suspense", "Aventura"], ano: 1996, classificacao: "PG-13", duracao: 110, popularidade: "popular", spoilerSensivel: false, sinopse: "Um agente é acusado de traição e precisa descobrir quem o incriminou enquanto foge dos próprios colegas." },
  { titulo: "Velozes e Furiosos", generos: ["Ação", "Suspense"], ano: 2001, classificacao: "14+", duracao: 106, popularidade: "popular", spoilerSensivel: false, sinopse: "Um policial infiltrado no mundo dos rachas de rua investiga uma onda de roubos de caminhões." },
  { titulo: "Ghost: Do Outro Lado da Vida", generos: ["Romance", "Fantasia", "Drama"], ano: 1990, classificacao: "PG-13", duracao: 127, popularidade: "popular", spoilerSensivel: false, sinopse: "Assassinado, um homem tenta proteger a namorada do mais além, com a ajuda de uma médium atrapalhada." },
  { titulo: "A Lista de Schindler", generos: ["Drama"], ano: 1993, classificacao: "16+", duracao: 195, popularidade: "popular", spoilerSensivel: false, sinopse: "Durante o Holocausto, um empresário alemão usa sua fábrica para salvar centenas de judeus." },
  { titulo: "Um Sonho de Liberdade", generos: ["Drama"], ano: 1994, classificacao: "16+", duracao: 142, popularidade: "popular", spoilerSensivel: false, sinopse: "Um banqueiro condenado injustamente constrói uma amizade duradoura na prisão enquanto mantém a esperança de liberdade." },
  { titulo: "O Rei Leão", generos: ["Animação", "Aventura", "Drama"], ano: 1994, classificacao: "PG", duracao: 88, popularidade: "popular", spoilerSensivel: false, sinopse: "Um jovem leão foge do reino após uma tragédia e precisa decidir se volta para assumir seu lugar." },
  { titulo: "Aladdin", generos: ["Animação", "Aventura", "Comédia", "Fantasia", "Romance"], ano: 1992, classificacao: "PG", duracao: 90, popularidade: "popular", spoilerSensivel: false, sinopse: "Um jovem ladrão encontra uma lâmpada mágica e um gênio que podem mudar seu destino e conquistar uma princesa." },
  { titulo: "Mulan", generos: ["Animação", "Aventura", "Ação", "Fantasia"], ano: 1998, classificacao: "PG", duracao: 88, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma jovem se disfarça de homem para ocupar o lugar do pai doente no exército imperial chinês." },
  { titulo: "Ace Ventura: Um Detetive Diferente", generos: ["Comédia"], ano: 1994, classificacao: "PG-13", duracao: 86, popularidade: "popular", spoilerSensivel: false, sinopse: "Um excêntrico detetive de animais é contratado para encontrar o mascote sequestrado de um time de futebol americano." },
  { titulo: "O Máskara", generos: ["Comédia", "Fantasia"], ano: 1994, classificacao: "PG-13", duracao: 101, popularidade: "popular", spoilerSensivel: false, sinopse: "Um bancário tímido encontra uma máscara mágica que o transforma em uma figura caótica e irresistível." },
  { titulo: "Debi & Lóide: Dois Idiotas em Apuros", generos: ["Comédia"], ano: 1994, classificacao: "PG-13", duracao: 107, popularidade: "popular", spoilerSensivel: false, sinopse: "Dois amigos nada espertos atravessam o país para devolver uma maleta esquecida, sem imaginar o que há dentro dela." },
  { titulo: "Zoolander", generos: ["Comédia"], ano: 2001, classificacao: "PG-13", duracao: 90, popularidade: "popular", spoilerSensivel: false, sinopse: "Um modelo bobo e em decadência é manipulado para participar de um plano para assassinar um líder mundial." },
  { titulo: "Escola de Rock", generos: ["Comédia"], ano: 2003, classificacao: "PG-13", duracao: 109, popularidade: "popular", spoilerSensivel: false, sinopse: "Um guitarrista desempregado finge ser professor substituto e transforma seus alunos em uma banda de rock." },
  { titulo: "A Era do Gelo", generos: ["Animação", "Comédia", "Aventura"], ano: 2002, classificacao: "PG", duracao: 81, popularidade: "popular", spoilerSensivel: false, sinopse: "Um mamute, uma preguiça e um tigre-dente-de-sabre devolvem um bebê humano à sua tribo durante a era glacial." },
  { titulo: "Madagascar", generos: ["Animação", "Comédia", "Aventura"], ano: 2005, classificacao: "PG", duracao: 86, popularidade: "popular", spoilerSensivel: false, sinopse: "Quatro animais do zoológico de Nova York acabam na selva de Madagascar e precisam se adaptar à vida selvagem." },
  { titulo: "Carros", generos: ["Animação", "Comédia", "Aventura"], ano: 2006, classificacao: "PG", duracao: 117, popularidade: "popular", spoilerSensivel: false, sinopse: "Um carro de corrida convencido fica preso em uma pequena cidade e aprende lições sobre amizade e humildade." },
  { titulo: "Kung Fu Panda", generos: ["Animação", "Ação", "Comédia", "Aventura"], ano: 2008, classificacao: "PG", duracao: 92, popularidade: "popular", spoilerSensivel: false, sinopse: "Um panda desajeitado e apaixonado por kung fu é escolhido para se tornar o Dragão Guerreiro." },
  { titulo: "Lilo & Stitch", generos: ["Animação", "Comédia", "Ficção Científica"], ano: 2002, classificacao: "PG", duracao: 85, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma menina havaiana adota um cachorro estranho que, na verdade, é um alienígena fugitivo." },
  { titulo: "Coraline e o Mundo Secreto", generos: ["Animação", "Fantasia", "Terror"], ano: 2009, classificacao: "PG", duracao: 100, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma menina descobre uma porta secreta em casa que leva a uma versão perfeita, mas sinistra, de sua vida." },
  { titulo: "Batman: O Cavaleiro das Trevas", generos: ["Ação", "Suspense", "Drama"], ano: 2008, classificacao: "PG-13", duracao: 152, popularidade: "popular", spoilerSensivel: false, sinopse: "Batman enfrenta o caos provocado por um criminoso imprevisível que testa os limites da lei e da moral em Gotham." },
  { titulo: "Homem de Ferro", generos: ["Ação", "Ficção Científica", "Aventura"], ano: 2008, classificacao: "PG-13", duracao: 126, popularidade: "popular", spoilerSensivel: false, sinopse: "Um bilionário fabricante de armas constrói uma armadura de alta tecnologia depois de ser capturado por terroristas." },
  { titulo: "Bastardos Inglórios", generos: ["Ação", "Drama", "Suspense"], ano: 2009, classificacao: "18+", duracao: 153, popularidade: "cult", spoilerSensivel: false, sinopse: "Na França ocupada, soldados judeus americanos e uma jovem cinéfila tramam separadamente contra a cúpula nazista." },
  { titulo: "Harry Potter e o Prisioneiro de Azkaban", generos: ["Fantasia", "Aventura"], ano: 2004, classificacao: "PG", duracao: 142, popularidade: "popular", spoilerSensivel: false, sinopse: "Harry descobre que um perigoso fugitivo de Azkaban tem ligação com seu passado e está solto perto de Hogwarts." },
  { titulo: "As Crônicas de Nárnia: O Leão, a Feiticeira e o Guarda-Roupa", generos: ["Fantasia", "Aventura"], ano: 2005, classificacao: "PG", duracao: 143, popularidade: "popular", spoilerSensivel: false, sinopse: "Quatro irmãos atravessam um guarda-roupa e chegam a um reino mágico dominado por uma feiticeira de gelo." },
  { titulo: "Peixe Grande e Suas Histórias Maravilhosas", generos: ["Fantasia", "Drama", "Aventura"], ano: 2003, classificacao: "PG-13", duracao: 125, popularidade: "cult", spoilerSensivel: false, sinopse: "Um filho tenta descobrir a verdade por trás das histórias fantásticas que o pai sempre contou." },
  { titulo: "Stardust: O Mistério da Estrela", generos: ["Fantasia", "Aventura", "Romance", "Comédia"], ano: 2007, classificacao: "PG-13", duracao: 127, popularidade: "cult", spoilerSensivel: false, sinopse: "Um jovem atravessa um muro para um reino mágico em busca de uma estrela caída, disputada por bruxas e príncipes." },
  { titulo: "Na Natureza Selvagem", generos: ["Aventura", "Drama"], ano: 2007, classificacao: "16+", duracao: 148, popularidade: "cult", spoilerSensivel: false, sinopse: "Um jovem recém-formado abandona tudo para viver sozinho na natureza do Alasca." },
  { titulo: "Moulin Rouge! Amor em Vermelho", generos: ["Romance", "Drama", "Comédia"], ano: 2001, classificacao: "PG-13", duracao: 127, popularidade: "popular", spoilerSensivel: false, sinopse: "Um escritor pobre se apaixona por uma cortesã famosa do cabaré mais badalado de Paris." },
  { titulo: "Pequena Miss Sunshine", generos: ["Comédia", "Drama"], ano: 2006, classificacao: "16+", duracao: 101, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma família disfuncional atravessa os Estados Unidos de kombi para levar a filha caçula a um concurso de beleza." },
  { titulo: "Cidade dos Sonhos", generos: ["Suspense", "Drama"], ano: 2001, classificacao: "16+", duracao: 147, popularidade: "cult", spoilerSensivel: true, sinopse: "Uma aspirante a atriz ajuda uma mulher com amnésia a descobrir quem ela é em uma Los Angeles enigmática." },
  { titulo: "O Menino do Pijama Listrado", generos: ["Drama"], ano: 2008, classificacao: "PG-13", duracao: 94, popularidade: "popular", spoilerSensivel: true, sinopse: "Durante a Segunda Guerra, o filho de um oficial nazista faz amizade com um garoto do outro lado de uma cerca." },

  // ===== Recentes (2010 em diante) =====
  { titulo: "Guardiões da Galáxia", generos: ["Ação", "Ficção Científica", "Aventura", "Comédia"], ano: 2014, classificacao: "PG-13", duracao: 121, popularidade: "popular", spoilerSensivel: false, sinopse: "Um grupo de desajustados se une para impedir que um vilão use uma poderosa esfera para destruir planetas." },
  { titulo: "Homem-Aranha: Sem Volta para Casa", generos: ["Ação", "Aventura", "Ficção Científica"], ano: 2021, classificacao: "PG-13", duracao: 148, popularidade: "popular", spoilerSensivel: true, sinopse: "Peter Parker pede ajuda a um mago para esconder sua identidade e acaba abrindo brechas entre universos." },
  { titulo: "Oppenheimer", generos: ["Drama", "Suspense"], ano: 2023, classificacao: "16+", duracao: 180, popularidade: "popular", spoilerSensivel: false, sinopse: "A história do físico que liderou o desenvolvimento da bomba atômica e as consequências dessa criação." },
  { titulo: "Barbie", generos: ["Comédia", "Fantasia", "Aventura"], ano: 2023, classificacao: "PG-13", duracao: 114, popularidade: "popular", spoilerSensivel: false, sinopse: "Em crise existencial na perfeita Barbieland, Barbie viaja ao mundo real em busca de respostas." },
  { titulo: "Top Gun: Maverick", generos: ["Ação", "Drama"], ano: 2022, classificacao: "PG-13", duracao: 130, popularidade: "popular", spoilerSensivel: false, sinopse: "Décadas depois, um piloto veterano volta à escola de elite para treinar jovens aviadores em uma missão arriscada." },
  { titulo: "Os Vingadores", generos: ["Ação", "Ficção Científica", "Aventura"], ano: 2012, classificacao: "PG-13", duracao: 143, popularidade: "popular", spoilerSensivel: false, sinopse: "Os maiores heróis da Terra se reúnem para impedir uma invasão alienígena liderada por Loki." },
  { titulo: "Batman", generos: ["Ação", "Suspense", "Drama"], ano: 2022, classificacao: "PG-13", duracao: 176, popularidade: "popular", spoilerSensivel: false, sinopse: "No segundo ano como vigilante, Batman investiga uma série de crimes que expõem a corrupção de Gotham." },
  { titulo: "Frozen: Uma Aventura Congelante", generos: ["Animação", "Fantasia", "Aventura", "Comédia"], ano: 2013, classificacao: "PG", duracao: 102, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma princesa parte em busca da irmã, rainha de poderes gelados, para acabar com o inverno eterno." },
  { titulo: "Moana: Um Mar de Aventuras", generos: ["Animação", "Aventura", "Fantasia", "Comédia"], ano: 2016, classificacao: "PG", duracao: 107, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma jovem polinésia atravessa o oceano com um semideus para salvar sua ilha." },
  { titulo: "Zootopia: Essa Cidade é o Bicho", generos: ["Animação", "Aventura", "Comédia"], ano: 2016, classificacao: "PG", duracao: 108, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma coelha policial e uma raposa trapaceira investigam juntos um mistério na cidade dos animais." },
  { titulo: "Coco", generos: ["Animação", "Fantasia", "Aventura", "Comédia"], ano: 2017, classificacao: "PG", duracao: 105, popularidade: "popular", spoilerSensivel: false, sinopse: "Durante o Dia dos Mortos, um menino que sonha ser músico entra na terra dos ancestrais." },
  { titulo: "Soul", generos: ["Animação", "Fantasia", "Comédia", "Drama"], ano: 2020, classificacao: "PG", duracao: 100, popularidade: "popular", spoilerSensivel: false, sinopse: "Um professor de música que sonha em tocar jazz tenta voltar à vida depois de um acidente." },
  { titulo: "Encanto", generos: ["Animação", "Fantasia", "Comédia"], ano: 2021, classificacao: "PG", duracao: 102, popularidade: "popular", spoilerSensivel: false, sinopse: "Em uma família colombiana onde todos têm dons mágicos, a única sem poderes tenta salvar a casa encantada." },
  { titulo: "Super Mario Bros. O Filme", generos: ["Animação", "Aventura", "Comédia"], ano: 2023, classificacao: "PG", duracao: 92, popularidade: "popular", spoilerSensivel: false, sinopse: "Dois encanadores de Nova York são levados a um mundo mágico e precisam enfrentar o rei dos Koopas." },
  { titulo: "Meu Malvado Favorito", generos: ["Animação", "Comédia", "Aventura"], ano: 2010, classificacao: "PG", duracao: 95, popularidade: "popular", spoilerSensivel: false, sinopse: "Um vilão pretende roubar a Lua, mas seus planos mudam quando adota três meninas." },
  { titulo: "Your Name.", generos: ["Animação", "Romance", "Fantasia", "Drama"], ano: 2016, classificacao: "PG", duracao: 106, popularidade: "popular", spoilerSensivel: true, sinopse: "Dois adolescentes que nunca se viram passam a trocar de corpo misteriosamente e tentam se encontrar." },
  { titulo: "Um Lugar Silencioso", generos: ["Terror", "Suspense", "Ficção Científica"], ano: 2018, classificacao: "14+", duracao: 90, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma família precisa viver em silêncio absoluto para escapar de criaturas que caçam pelo som." },
  { titulo: "Invocação do Mal", generos: ["Terror", "Suspense"], ano: 2013, classificacao: "16+", duracao: 112, popularidade: "popular", spoilerSensivel: false, sinopse: "Um casal de investigadores paranormais ajuda uma família aterrorizada por uma presença maligna em uma fazenda." },
  { titulo: "It: A Coisa", generos: ["Terror", "Suspense"], ano: 2017, classificacao: "16+", duracao: 135, popularidade: "popular", spoilerSensivel: false, sinopse: "Um grupo de crianças enfrenta uma entidade que assume a forma de um palhaço e ataca a cidade a cada geração." },
  { titulo: "Midsommar: O Mal Não Espera a Noite", generos: ["Terror", "Drama"], ano: 2019, classificacao: "18+", duracao: 148, popularidade: "cult", spoilerSensivel: false, sinopse: "Um casal em crise viaja para um festival de verão em uma comunidade isolada na Suécia." },
  { titulo: "O Farol", generos: ["Terror", "Drama", "Fantasia"], ano: 2019, classificacao: "16+", duracao: 109, popularidade: "cult", spoilerSensivel: false, sinopse: "Dois faroleiros isolados em uma ilha no século XIX perdem aos poucos a sanidade." },
  { titulo: "Nós", generos: ["Terror", "Suspense"], ano: 2019, classificacao: "16+", duracao: 116, popularidade: "popular", spoilerSensivel: true, sinopse: "Durante as férias, uma família é atacada por sósias que surgem em sua casa à noite." },
  { titulo: "Fale Comigo", generos: ["Terror", "Suspense"], ano: 2023, classificacao: "16+", duracao: 95, popularidade: "popular", spoilerSensivel: false, sinopse: "Um grupo de amigos descobre um jogo que permite invocar espíritos e passa a sofrer as consequências." },
  { titulo: "Sorria", generos: ["Terror", "Suspense"], ano: 2022, classificacao: "16+", duracao: 115, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma psiquiatra começa a ser assombrada por uma entidade após presenciar um evento traumático de uma paciente." },
  { titulo: "O Babadook", generos: ["Terror", "Drama", "Suspense"], ano: 2014, classificacao: "16+", duracao: 94, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma mãe viúva e seu filho são perseguidos por uma criatura que surge de um misterioso livro infantil." },
  { titulo: "Bird Box", generos: ["Terror", "Suspense", "Ficção Científica"], ano: 2018, classificacao: "16+", duracao: 124, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma mulher tenta levar duas crianças rio abaixo de olhos vendados para escapar de uma ameaça invisível." },
  { titulo: "Ela", generos: ["Romance", "Drama", "Ficção Científica"], ano: 2013, classificacao: "16+", duracao: 126, popularidade: "cult", spoilerSensivel: false, sinopse: "Um escritor solitário se apaixona por uma inteligência artificial de voz envolvente." },
  { titulo: "A Culpa é das Estrelas", generos: ["Romance", "Drama"], ano: 2014, classificacao: "PG-13", duracao: 126, popularidade: "popular", spoilerSensivel: false, sinopse: "Dois adolescentes que se conhecem em um grupo de apoio vivem um romance cheio de intensidade." },
  { titulo: "Questão de Tempo", generos: ["Romance", "Comédia", "Fantasia", "Drama"], ano: 2013, classificacao: "14+", duracao: 123, popularidade: "popular", spoilerSensivel: false, sinopse: "Um jovem descobre que os homens da família podem voltar no tempo e usa o dom para conquistar o amor." },
  { titulo: "Para Todos os Garotos que Já Amei", generos: ["Romance", "Comédia"], ano: 2018, classificacao: "PG", duracao: 99, popularidade: "popular", spoilerSensivel: false, sinopse: "Cartas de amor secretas de uma adolescente são enviadas por engano aos antigos crushes dela." },
  { titulo: "Me Chame pelo Seu Nome", generos: ["Romance", "Drama"], ano: 2017, classificacao: "16+", duracao: 132, popularidade: "cult", spoilerSensivel: false, sinopse: "No verão italiano dos anos 80, um jovem de 17 anos se envolve com o assistente de seu pai." },
  { titulo: "Moonlight: Sob a Luz do Luar", generos: ["Drama"], ano: 2016, classificacao: "16+", duracao: 111, popularidade: "cult", spoilerSensivel: false, sinopse: "A vida de um jovem negro de Miami é contada em três fases, da infância à idade adulta, em busca de identidade." },
  { titulo: "Anora", generos: ["Comédia", "Romance", "Drama"], ano: 2024, classificacao: "18+", duracao: 139, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma dançarina de Nova York se casa impulsivamente com o filho de um oligarca russo e enfrenta as consequências." },
  { titulo: "Ainda Estou Aqui", generos: ["Drama"], ano: 2024, classificacao: "14+", duracao: 137, popularidade: "popular", spoilerSensivel: false, sinopse: "Nos anos 1970, uma mãe luta para reconstruir a família e descobrir a verdade após o desaparecimento do marido durante a ditadura." },
  { titulo: "Pobres Criaturas", generos: ["Comédia", "Drama", "Ficção Científica"], ano: 2023, classificacao: "18+", duracao: 141, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma jovem trazida de volta à vida por um cientista excêntrico parte para uma jornada de descobertas pelo mundo." },
  { titulo: "Wicked", generos: ["Fantasia", "Romance", "Drama"], ano: 2024, classificacao: "PG", duracao: 160, popularidade: "popular", spoilerSensivel: false, sinopse: "Antes de Dorothy, duas jovens bruxas com personalidades opostas se conhecem na escola e formam uma amizade improvável." },
  { titulo: "Duna: Parte Dois", generos: ["Ficção Científica", "Aventura", "Ação", "Drama"], ano: 2024, classificacao: "PG-13", duracao: 166, popularidade: "popular", spoilerSensivel: false, sinopse: "Paul Atreides se une aos Fremen para vingar a família e impedir um futuro terrível." },
  { titulo: "Tudo em Todo Lugar ao Mesmo Tempo", generos: ["Ficção Científica", "Comédia", "Ação", "Drama"], ano: 2022, classificacao: "16+", duracao: 139, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma dona de lavanderia é arrastada para uma aventura caótica por múltiplos universos para salvar a realidade." },
  { titulo: "Entre Facas e Segredos", generos: ["Suspense", "Comédia", "Drama"], ano: 2019, classificacao: "PG-13", duracao: 130, popularidade: "popular", spoilerSensivel: false, sinopse: "Um detetive investiga a morte de um escritor milionário cercado de uma família cheia de segredos." },
  { titulo: "Bacurau", generos: ["Suspense", "Drama", "Ação"], ano: 2019, classificacao: "18+", duracao: 131, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma pequena cidade do sertão começa a desaparecer do mapa e seus moradores precisam se unir para se defender." },
  { titulo: "Cisne Negro", generos: ["Suspense", "Drama", "Terror"], ano: 2010, classificacao: "16+", duracao: 108, popularidade: "cult", spoilerSensivel: true, sinopse: "Uma bailarina perfeccionista é escolhida para o papel principal de O Lago dos Cisnes e entra em colapso psicológico." },
  { titulo: "Ilha do Medo", generos: ["Suspense", "Drama"], ano: 2010, classificacao: "16+", duracao: 138, popularidade: "popular", spoilerSensivel: true, sinopse: "Um agente investiga o desaparecimento de uma paciente em um hospital psiquiátrico isolado em uma ilha." },
  { titulo: "Os Suspeitos: Prisioneiros", generos: ["Suspense", "Drama"], ano: 2013, classificacao: "16+", duracao: 153, popularidade: "cult", spoilerSensivel: false, sinopse: "Quando a filha de um pai desesperado desaparece, ele toma a investigação nas próprias mãos." },
  { titulo: "Gravidade", generos: ["Ficção Científica", "Suspense", "Drama"], ano: 2013, classificacao: "PG-13", duracao: 91, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma engenheira e um astronauta ficam à deriva no espaço após um acidente com detritos." },
  { titulo: "Perdido em Marte", generos: ["Ficção Científica", "Aventura", "Drama"], ano: 2015, classificacao: "PG-13", duracao: 144, popularidade: "popular", spoilerSensivel: false, sinopse: "Um astronauta é dado como morto e abandonado em Marte e precisa descobrir como sobreviver até um resgate." },
  { titulo: "A Chegada", generos: ["Ficção Científica", "Drama"], ano: 2016, classificacao: "PG-13", duracao: 116, popularidade: "cult", spoilerSensivel: true, sinopse: "Uma linguista é chamada para decifrar a comunicação de alienígenas que pousaram em diferentes pontos da Terra." },
  { titulo: "Django Livre", generos: ["Ação", "Drama", "Aventura"], ano: 2012, classificacao: "18+", duracao: 165, popularidade: "popular", spoilerSensivel: false, sinopse: "Um ex-escravo e um caçador de recompensas se unem para resgatar a esposa dele de um fazendeiro cruel." },
  { titulo: "O Lobo de Wall Street", generos: ["Comédia", "Drama"], ano: 2013, classificacao: "18+", duracao: 180, popularidade: "popular", spoilerSensivel: false, sinopse: "A ascensão e a queda de um corretor da bolsa envolvido em fraudes, luxo e excessos." },
  { titulo: "Meia-Noite em Paris", generos: ["Romance", "Comédia", "Fantasia"], ano: 2011, classificacao: "PG-13", duracao: 94, popularidade: "cult", spoilerSensivel: false, sinopse: "Um roteirista em viagem a Paris é transportado todas as noites para os anos 20 e conhece grandes artistas." },
  { titulo: "Intocáveis", generos: ["Comédia", "Drama"], ano: 2011, classificacao: "14+", duracao: 112, popularidade: "popular", spoilerSensivel: false, sinopse: "Um aristocrata tetraplégico contrata um jovem sem experiência como cuidador, e os dois constroem uma amizade inesperada." },
  { titulo: "Lady Bird: A Hora de Voar", generos: ["Comédia", "Drama"], ano: 2017, classificacao: "16+", duracao: 94, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma adolescente do último ano do ensino médio tenta lidar com a relação conturbada com a mãe e o desejo de sair da cidade." },
  { titulo: "A Forma da Água", generos: ["Fantasia", "Romance", "Drama"], ano: 2017, classificacao: "16+", duracao: 123, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma faxineira muda de um laboratório secreto se apaixona por uma criatura aquática mantida em cativeiro." },
  { titulo: "Jumanji: Bem-Vindo à Selva", generos: ["Aventura", "Comédia", "Ação"], ano: 2017, classificacao: "PG-13", duracao: 119, popularidade: "popular", spoilerSensivel: false, sinopse: "Quatro adolescentes são sugados para um videogame e precisam vencer o jogo nos corpos dos avatares." },
  { titulo: "A Vida Secreta de Walter Mitty", generos: ["Aventura", "Comédia", "Drama"], ano: 2013, classificacao: "PG", duracao: 114, popularidade: "popular", spoilerSensivel: false, sinopse: "Um funcionário sonhador troca a rotina por uma viagem real pelo mundo para encontrar um negativo perdido." },
  { titulo: "As Aventuras de Pi", generos: ["Aventura", "Drama", "Fantasia"], ano: 2012, classificacao: "PG", duracao: 127, popularidade: "popular", spoilerSensivel: false, sinopse: "Um jovem indiano sobrevive a um naufrágio e fica à deriva no oceano ao lado de um tigre-de-bengala." },
  { titulo: "O Regresso", generos: ["Aventura", "Drama", "Ação"], ano: 2015, classificacao: "18+", duracao: 156, popularidade: "popular", spoilerSensivel: false, sinopse: "Um caçador ferido e abandonado na natureza selvagem luta para sobreviver e se vingar." },
  { titulo: "Free Guy: Assumindo o Controle", generos: ["Comédia", "Ação", "Ficção Científica"], ano: 2021, classificacao: "PG-13", duracao: 115, popularidade: "popular", spoilerSensivel: false, sinopse: "Um personagem de fundo de um videogame percebe que vive em um jogo e decide se tornar o herói." },
  { titulo: "Deadpool", generos: ["Ação", "Comédia"], ano: 2016, classificacao: "18+", duracao: 108, popularidade: "popular", spoilerSensivel: false, sinopse: "Um mercenário debochado ganha poderes de cura e parte atrás do homem que destruiu sua vida." },
  { titulo: "Missão: Impossível - Efeito Fallout", generos: ["Ação", "Suspense", "Aventura"], ano: 2018, classificacao: "PG-13", duracao: 147, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma missão dá errado e a equipe de Ethan Hunt corre contra o tempo para evitar uma catástrofe global." },
  { titulo: "Kingsman: Serviço Secreto", generos: ["Ação", "Comédia", "Aventura"], ano: 2014, classificacao: "16+", duracao: 129, popularidade: "popular", spoilerSensivel: false, sinopse: "Um jovem de origem humilde é recrutado por uma agência de espiões britânica para impedir um magnata de plano mortal." },
  { titulo: "Logan", generos: ["Ação", "Drama", "Ficção Científica"], ano: 2017, classificacao: "16+", duracao: 137, popularidade: "popular", spoilerSensivel: false, sinopse: "Em um futuro sombrio, um Wolverine envelhecido protege uma jovem mutante perseguida." },
  { titulo: "Capitão América: O Soldado Invernal", generos: ["Ação", "Ficção Científica", "Aventura", "Suspense"], ano: 2014, classificacao: "PG-13", duracao: 136, popularidade: "popular", spoilerSensivel: false, sinopse: "Steve Rogers descobre uma conspiração na S.H.I.E.L.D. enquanto enfrenta um misterioso assassino." },
  { titulo: "O Hobbit: Uma Jornada Inesperada", generos: ["Fantasia", "Aventura"], ano: 2012, classificacao: "PG-13", duracao: 169, popularidade: "popular", spoilerSensivel: false, sinopse: "Um hobbit pacato é convidado por um mago e treze anões para recuperar um tesouro guardado por um dragão." },
  { titulo: "Animais Fantásticos e Onde Habitam", generos: ["Fantasia", "Aventura"], ano: 2016, classificacao: "PG-13", duracao: 133, popularidade: "popular", spoilerSensivel: false, sinopse: "Um magizoologista chega a Nova York com uma maleta repleta de criaturas mágicas que acabam escapando." },
  { titulo: "Missão Madrinha de Casamento", generos: ["Comédia", "Romance"], ano: 2011, classificacao: "16+", duracao: 125, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma mulher em crise é escolhida como madrinha da melhor amiga e vê sua vida virar de cabeça para baixo." },
  { titulo: "Minha Mãe é uma Peça", generos: ["Comédia"], ano: 2013, classificacao: "14+", duracao: 85, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma mãe superprotetora e cheia de manias tira os filhos do sério em situações hilárias do dia a dia." },
  { titulo: "Que Horas Ela Volta?", generos: ["Drama", "Comédia"], ano: 2015, classificacao: "14+", duracao: 112, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma empregada doméstica vê a rotina da casa mudar com a chegada da filha, que não aceita as regras não ditas da família." },
  // ===== Filmes longos (mais de 140 min) =====
  // Cole estas linhas dentro do array FILMES, antes do "];" final.

  // --- Clássicos (antes de 1990) ---
  { titulo: "Lawrence da Arábia", generos: ["Aventura", "Drama"], ano: 1962, classificacao: "PG", duracao: 227, popularidade: "cult", spoilerSensivel: false, sinopse: "Um oficial britânico se une às tribos árabes e lidera uma revolta contra o Império Otomano no deserto." },
  { titulo: "Ben-Hur", generos: ["Drama", "Aventura", "Ação"], ano: 1959, classificacao: "PG", duracao: 212, popularidade: "cult", spoilerSensivel: false, sinopse: "Um nobre judeu traído por um amigo de infância é escravizado e busca vingança, culminando em uma corrida de bigas lendária." },
  { titulo: "O Poderoso Chefão: Parte II", generos: ["Drama", "Suspense"], ano: 1974, classificacao: "16+", duracao: 202, popularidade: "cult", spoilerSensivel: false, sinopse: "Michael Corleone expande o império da família enquanto a história mostra a juventude de seu pai na Sicília e em Nova York." },
  { titulo: "Os Sete Samurais", generos: ["Ação", "Aventura", "Drama"], ano: 1954, classificacao: "14+", duracao: 207, popularidade: "cult", spoilerSensivel: false, sinopse: "Camponeses contratam sete samurais para proteger sua aldeia de bandidos que voltam todos os anos para saquear a colheita." },
  { titulo: "Spartacus", generos: ["Drama", "Ação", "Aventura"], ano: 1960, classificacao: "14+", duracao: 197, popularidade: "cult", spoilerSensivel: false, sinopse: "Um escravo treinado como gladiador lidera uma grande revolta contra a República Romana." },
  { titulo: "Cleópatra", generos: ["Drama", "Romance"], ano: 1963, classificacao: "PG", duracao: 192, popularidade: "cult", spoilerSensivel: false, sinopse: "A rainha do Egito se envolve com Júlio César e Marco Antônio em meio a disputas de poder entre Roma e o Oriente." },
  { titulo: "Doutor Jivago", generos: ["Romance", "Drama"], ano: 1965, classificacao: "14+", duracao: 197, popularidade: "cult", spoilerSensivel: false, sinopse: "Um médico e poeta vive um grande amor em meio à Revolução Russa e à guerra civil." },
  { titulo: "Gandhi", generos: ["Drama"], ano: 1982, classificacao: "PG", duracao: 191, popularidade: "cult", spoilerSensivel: false, sinopse: "A trajetória do advogado que liderou a independência da Índia por meio da resistência pacífica." },
  { titulo: "Amadeus", generos: ["Drama"], ano: 1984, classificacao: "14+", duracao: 160, popularidade: "cult", spoilerSensivel: false, sinopse: "Um compositor da corte austríaca, consumido pela inveja, narra sua rivalidade com o jovem gênio Mozart." },
  { titulo: "Era Uma Vez na América", generos: ["Drama", "Suspense"], ano: 1984, classificacao: "18+", duracao: 229, popularidade: "cult", spoilerSensivel: false, sinopse: "Um ex-gângster judeu relembra a amizade, o crime e as traições que marcaram sua vida no submundo de Nova York." },
  { titulo: "Scarface: A Cara do Crime", generos: ["Drama", "Suspense", "Ação"], ano: 1983, classificacao: "18+", duracao: 170, popularidade: "cult", spoilerSensivel: false, sinopse: "Um imigrante cubano ambicioso sobe rapidamente no tráfico de drogas de Miami e é consumido pelo próprio poder." },
  { titulo: "O Franco Atirador", generos: ["Drama"], ano: 1978, classificacao: "18+", duracao: 183, popularidade: "cult", spoilerSensivel: false, sinopse: "Três amigos de uma cidade operária americana têm suas vidas mudadas para sempre pela Guerra do Vietnã." },
  { titulo: "Os Dez Mandamentos", generos: ["Drama", "Aventura"], ano: 1956, classificacao: "PG", duracao: 220, popularidade: "cult", spoilerSensivel: false, sinopse: "A vida de Moisés, do príncipe criado no Egito ao líder que conduz o povo hebreu rumo à liberdade." },
  { titulo: "A Noviça Rebelde", generos: ["Romance", "Drama", "Comédia"], ano: 1965, classificacao: "PG", duracao: 174, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma noviça se torna governanta dos sete filhos de um capitão viúvo na Áustria às vésperas da Segunda Guerra." },
  { titulo: "Amor, Sublime Amor (1961)", generos: ["Romance", "Drama"], ano: 1961, classificacao: "14+", duracao: 152, popularidade: "cult", spoilerSensivel: false, sinopse: "Um romance entre jovens de gangues rivais em Nova York ecoa a tragédia de Romeu e Julieta." },
  { titulo: "Minha Bela Dama", generos: ["Romance", "Comédia", "Drama"], ano: 1964, classificacao: "PG", duracao: 170, popularidade: "cult", spoilerSensivel: false, sinopse: "Um professor de fonética aposta que consegue transformar uma vendedora de flores em uma dama da alta sociedade." },
  { titulo: "Cinema Paradiso", generos: ["Drama", "Romance"], ano: 1988, classificacao: "14+", duracao: 155, popularidade: "cult", spoilerSensivel: false, sinopse: "Um cineasta relembra a infância em uma vila italiana e a amizade com o projecionista do cinema local." },
  { titulo: "Três Homens em Conflito", generos: ["Ação", "Aventura", "Drama"], ano: 1966, classificacao: "16+", duracao: 178, popularidade: "cult", spoilerSensivel: false, sinopse: "Três pistoleiros disputam um tesouro enterrado em um cemitério durante a Guerra Civil americana." },
  { titulo: "Era Uma Vez no Oeste", generos: ["Ação", "Drama", "Aventura"], ano: 1968, classificacao: "14+", duracao: 165, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma viúva, um pistoleiro misterioso e um bandido se envolvem na disputa por terras onde passará a ferrovia." },
  { titulo: "Solaris", generos: ["Ficção Científica", "Drama"], ano: 1972, classificacao: "14+", duracao: 167, popularidade: "cult", spoilerSensivel: false, sinopse: "Um psicólogo é enviado a uma estação espacial em órbita de um planeta que materializa as memórias dos astronautas." },
  { titulo: "Stalker", generos: ["Ficção Científica", "Drama"], ano: 1979, classificacao: "14+", duracao: 162, popularidade: "cult", spoilerSensivel: false, sinopse: "Um guia leva um escritor e um cientista a uma zona proibida onde existiria um quarto capaz de realizar desejos." },

  // --- Modernos (1990 a 2009) ---
  { titulo: "Os Bons Companheiros", generos: ["Drama", "Suspense"], ano: 1990, classificacao: "18+", duracao: 146, popularidade: "cult", spoilerSensivel: false, sinopse: "A ascensão e a queda de um jovem que cresce admirando a máfia italiana em Nova York." },
  { titulo: "Cassino", generos: ["Drama", "Suspense"], ano: 1995, classificacao: "18+", duracao: 178, popularidade: "cult", spoilerSensivel: false, sinopse: "Um apostador genial assume o comando de um cassino de Las Vegas controlado pela máfia, mas o poder e a violência cobram seu preço." },
  { titulo: "Coração Valente", generos: ["Ação", "Drama", "Aventura"], ano: 1995, classificacao: "18+", duracao: 178, popularidade: "popular", spoilerSensivel: false, sinopse: "Um guerreiro escocês lidera seu povo em uma rebelião contra a dominação inglesa no século XIII." },
  { titulo: "Fogo Contra Fogo", generos: ["Ação", "Suspense", "Drama"], ano: 1995, classificacao: "18+", duracao: 170, popularidade: "cult", spoilerSensivel: false, sinopse: "Um tenente obstinado persegue um ladrão profissional e sua equipe pelas ruas de Los Angeles." },
  { titulo: "O Resgate do Soldado Ryan", generos: ["Ação", "Drama"], ano: 1998, classificacao: "16+", duracao: 169, popularidade: "popular", spoilerSensivel: false, sinopse: "Após o Dia D, um grupo de soldados é enviado para trazer de volta um paraquedista cujos irmãos morreram em combate." },
  { titulo: "À Espera de um Milagre", generos: ["Drama", "Fantasia"], ano: 1999, classificacao: "16+", duracao: 189, popularidade: "popular", spoilerSensivel: false, sinopse: "Um guarda de prisão descobre que um condenado à morte tem poderes extraordinários." },
  { titulo: "Magnólia", generos: ["Drama"], ano: 1999, classificacao: "16+", duracao: 188, popularidade: "cult", spoilerSensivel: false, sinopse: "Vidas de moradores de Los Angeles se cruzam em um único dia marcado por arrependimentos e reencontros." },
  { titulo: "Gangues de Nova York", generos: ["Drama", "Ação"], ano: 2002, classificacao: "18+", duracao: 167, popularidade: "cult", spoilerSensivel: false, sinopse: "No século XIX, um jovem volta a Nova York para vingar a morte do pai, líder de uma gangue rival." },
  { titulo: "O Aviador", generos: ["Drama"], ano: 2004, classificacao: "14+", duracao: 170, popularidade: "popular", spoilerSensivel: false, sinopse: "A ascensão do bilionário Howard Hughes no cinema e na aviação, enquanto lida com seus distúrbios psicológicos." },
  { titulo: "King Kong", generos: ["Aventura", "Ação"], ano: 2005, classificacao: "PG-13", duracao: 187, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma equipe de filmagem chega a uma ilha misteriosa e leva para Nova York um gigantesco gorila." },
  { titulo: "Piratas do Caribe: O Baú da Morte", generos: ["Aventura", "Ação", "Fantasia", "Comédia"], ano: 2006, classificacao: "PG-13", duracao: 151, popularidade: "popular", spoilerSensivel: false, sinopse: "Jack Sparrow precisa quitar uma dívida com o capitão do Holandês Voador e procura um misterioso baú." },
  { titulo: "Piratas do Caribe: No Fim do Mundo", generos: ["Aventura", "Ação", "Fantasia"], ano: 2007, classificacao: "PG-13", duracao: 169, popularidade: "popular", spoilerSensivel: true, sinopse: "Piratas e a Companhia das Índias Orientais se enfrentam em uma batalha pelo controle dos mares." },
  { titulo: "O Senhor dos Anéis: As Duas Torres", generos: ["Fantasia", "Aventura", "Ação"], ano: 2002, classificacao: "PG-13", duracao: 179, popularidade: "popular", spoilerSensivel: false, sinopse: "A Sociedade do Anel se separa enquanto Frodo e Sam seguem rumo a Mordor e o reino de Rohan se prepara para a guerra." },
  { titulo: "Armageddon", generos: ["Ação", "Ficção Científica", "Aventura"], ano: 1998, classificacao: "PG-13", duracao: 151, popularidade: "popular", spoilerSensivel: false, sinopse: "Um grupo de perfuradores de petróleo é enviado ao espaço para destruir um asteroide em rota de colisão com a Terra." },
  { titulo: "Pearl Harbor", generos: ["Drama", "Romance", "Ação"], ano: 2001, classificacao: "PG-13", duracao: 183, popularidade: "popular", spoilerSensivel: false, sinopse: "Dois pilotos amigos e uma enfermeira vivem um triângulo amoroso antes e depois do ataque japonês a Pearl Harbor." },
  { titulo: "Tróia", generos: ["Ação", "Aventura", "Drama"], ano: 2004, classificacao: "16+", duracao: 163, popularidade: "popular", spoilerSensivel: false, sinopse: "Uma guerra épica começa quando o príncipe de Tróia foge com a rainha de Esparta, e Aquiles lidera os gregos." },
  { titulo: "Cruzada", generos: ["Ação", "Aventura", "Drama"], ano: 2005, classificacao: "16+", duracao: 144, popularidade: "cult", spoilerSensivel: false, sinopse: "Um ferreiro francês viaja a Jerusalém na época das Cruzadas e se vê no centro de um conflito entre cristãos e muçulmanos." },
  { titulo: "O Pianista", generos: ["Drama"], ano: 2002, classificacao: "16+", duracao: 150, popularidade: "cult", spoilerSensivel: false, sinopse: "Um pianista judeu luta para sobreviver ao gueto e à ocupação nazista de Varsóvia." },
  { titulo: "Os Infiltrados", generos: ["Suspense", "Drama", "Ação"], ano: 2006, classificacao: "18+", duracao: 151, popularidade: "popular", spoilerSensivel: false, sinopse: "Um policial infiltrado na máfia e um mafioso infiltrado na polícia tentam descobrir a identidade um do outro." },
  { titulo: "Harry Potter e o Cálice de Fogo", generos: ["Fantasia", "Aventura"], ano: 2005, classificacao: "PG-13", duracao: 157, popularidade: "popular", spoilerSensivel: false, sinopse: "Harry é inesperadamente escolhido para um perigoso torneio entre três escolas de magia." },
  { titulo: "Harry Potter e a Câmara Secreta", generos: ["Fantasia", "Aventura"], ano: 2002, classificacao: "PG", duracao: 161, popularidade: "popular", spoilerSensivel: false, sinopse: "Em seu segundo ano em Hogwarts, Harry investiga ataques misteriosos ligados à lendária Câmara Secreta." },
  { titulo: "Harry Potter e o Enigma do Príncipe", generos: ["Fantasia", "Aventura"], ano: 2009, classificacao: "PG", duracao: 153, popularidade: "popular", spoilerSensivel: false, sinopse: "Dumbledore prepara Harry para a batalha final contra Voldemort enquanto ele encontra um livro misterioso." },
  { titulo: "O Último Samurai", generos: ["Ação", "Drama", "Aventura"], ano: 2003, classificacao: "16+", duracao: 154, popularidade: "popular", spoilerSensivel: false, sinopse: "Um capitão americano contratado para treinar o exército japonês acaba conhecendo e admirando os samurais." },
  { titulo: "Transformers", generos: ["Ação", "Ficção Científica", "Aventura"], ano: 2007, classificacao: "PG-13", duracao: 144, popularidade: "popular", spoilerSensivel: false, sinopse: "Um adolescente se envolve na guerra entre robôs alienígenas que chegam à Terra em busca de um poderoso artefato." },
  { titulo: "Avatar", generos: ["Ficção Científica", "Aventura", "Ação"], ano: 2009, classificacao: "PG-13", duracao: 162, popularidade: "popular", spoilerSensivel: false, sinopse: "Um ex-fuzileiro é enviado ao planeta Pandora e se divide entre a missão humana e o povo nativo Na'vi." },
  { titulo: "Independence Day", generos: ["Ficção Científica", "Ação", "Aventura"], ano: 1996, classificacao: "PG-13", duracao: 145, popularidade: "popular", spoilerSensivel: false, sinopse: "Naves alienígenas gigantes aparecem sobre grandes cidades e a humanidade tenta reagir antes de ser aniquilada." },
  { titulo: "Contato", generos: ["Ficção Científica", "Drama"], ano: 1997, classificacao: "PG", duracao: 150, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma astrônoma capta um sinal extraterrestre e precisa lidar com as dúvidas da ciência, da religião e do governo." },
  { titulo: "Dança com Lobos", generos: ["Drama", "Aventura"], ano: 1990, classificacao: "14+", duracao: 181, popularidade: "popular", spoilerSensivel: false, sinopse: "Um oficial da Guerra Civil se isola na fronteira e passa a conviver com uma tribo sioux." },
  { titulo: "O Paciente Inglês", generos: ["Romance", "Drama"], ano: 1996, classificacao: "16+", duracao: 162, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma enfermeira cuida de um homem gravemente queimado e descobre, por suas lembranças, uma história de amor proibido." },
  { titulo: "O Curioso Caso de Benjamin Button", generos: ["Romance", "Drama", "Fantasia"], ano: 2008, classificacao: "PG-13", duracao: 166, popularidade: "popular", spoilerSensivel: false, sinopse: "Um homem nasce com a aparência de um idoso e rejuvena com o passar dos anos." },
  { titulo: "As Crônicas de Nárnia: Príncipe Caspian", generos: ["Fantasia", "Aventura"], ano: 2008, classificacao: "PG", duracao: 150, popularidade: "popular", spoilerSensivel: false, sinopse: "Os irmãos Pevensie voltam a Nárnia e ajudam um príncipe a retomar o trono." },
  { titulo: "Star Wars: Ataque dos Clones", generos: ["Ficção Científica", "Aventura", "Ação"], ano: 2002, classificacao: "PG", duracao: 142, popularidade: "popular", spoilerSensivel: false, sinopse: "Obi-Wan investiga uma conspiração enquanto Anakin protege uma senadora e se aproxima do lado sombrio." },

  // --- Recentes (2010 em diante) ---
  { titulo: "O Hobbit: A Desolação de Smaug", generos: ["Fantasia", "Aventura"], ano: 2013, classificacao: "PG-13", duracao: 161, popularidade: "popular", spoilerSensivel: false, sinopse: "Bilbo e os anões seguem rumo à Montanha Solitária para enfrentar o dragão Smaug." },
  { titulo: "O Hobbit: A Batalha dos Cinco Exércitos", generos: ["Fantasia", "Aventura", "Ação"], ano: 2014, classificacao: "PG-13", duracao: 144, popularidade: "popular", spoilerSensivel: true, sinopse: "Diversos povos disputam o tesouro da Montanha Solitária em uma grande batalha." },
  { titulo: "Harry Potter e as Relíquias da Morte: Parte 1", generos: ["Fantasia", "Aventura"], ano: 2010, classificacao: "PG-13", duracao: 146, popularidade: "popular", spoilerSensivel: false, sinopse: "Harry, Rony e Hermione abandonam Hogwarts para caçar as horcruxes de Voldemort." },
  { titulo: "Os Miseráveis", generos: ["Drama", "Romance"], ano: 2012, classificacao: "PG-13", duracao: 158, popularidade: "popular", spoilerSensivel: false, sinopse: "Na França do século XIX, um ex-prisioneiro tenta recomeçar a vida enquanto é perseguido por um inspetor implacável." },
  { titulo: "Star Wars: Os Últimos Jedi", generos: ["Ficção Científica", "Aventura", "Ação"], ano: 2017, classificacao: "PG-13", duracao: 152, popularidade: "popular", spoilerSensivel: false, sinopse: "Rey busca orientação de Luke Skywalker enquanto a Resistência é caçada pela Primeira Ordem." },
  { titulo: "Star Wars: A Ascensão Skywalker", generos: ["Ficção Científica", "Aventura", "Ação"], ano: 2019, classificacao: "PG-13", duracao: 142, popularidade: "popular", spoilerSensivel: true, sinopse: "A Resistência e a Primeira Ordem se enfrentam em um confronto final que encerra a saga Skywalker." },
  { titulo: "Avatar: O Caminho da Água", generos: ["Ficção Científica", "Aventura", "Ação"], ano: 2022, classificacao: "PG-13", duracao: 192, popularidade: "popular", spoilerSensivel: false, sinopse: "Jake Sully e sua família fogem para os recifes de Pandora quando a ameaça humana retorna." },
  { titulo: "Vingadores: Guerra Infinita", generos: ["Ação", "Ficção Científica", "Aventura"], ano: 2018, classificacao: "PG-13", duracao: 149, popularidade: "popular", spoilerSensivel: true, sinopse: "Os heróis tentam impedir Thanos de coletar as Joias do Infinito." },
  { titulo: "Vingadores: Era de Ultron", generos: ["Ação", "Ficção Científica", "Aventura"], ano: 2015, classificacao: "PG-13", duracao: 141, popularidade: "popular", spoilerSensivel: false, sinopse: "Os Vingadores enfrentam uma inteligência artificial criada por Tony Stark que decide destruir a humanidade." },
  { titulo: "Capitão América: Guerra Civil", generos: ["Ação", "Ficção Científica", "Aventura"], ano: 2016, classificacao: "PG-13", duracao: 147, popularidade: "popular", spoilerSensivel: false, sinopse: "Um acordo para controlar os super-heróis divide os Vingadores em dois lados opostos." },
  { titulo: "Batman vs Superman: A Origem da Justiça", generos: ["Ação", "Aventura", "Ficção Científica"], ano: 2016, classificacao: "PG-13", duracao: 151, popularidade: "popular", spoilerSensivel: false, sinopse: "Batman e Superman se enfrentam enquanto uma nova ameaça surge em Metrópolis." },
  { titulo: "Pantera Negra: Wakanda Para Sempre", generos: ["Ação", "Aventura", "Drama", "Ficção Científica"], ano: 2022, classificacao: "PG-13", duracao: 161, popularidade: "popular", spoilerSensivel: false, sinopse: "Wakanda enfrenta uma nova ameaça enquanto o país tenta seguir em frente após a perda de seu rei." },
  { titulo: "Mulher-Maravilha", generos: ["Ação", "Aventura", "Fantasia"], ano: 2017, classificacao: "PG-13", duracao: 141, popularidade: "popular", spoilerSensivel: false, sinopse: "A princesa das amazonas deixa sua ilha para ajudar a acabar com a Primeira Guerra Mundial." },
  { titulo: "Batman: O Cavaleiro das Trevas Ressurge", generos: ["Ação", "Suspense", "Drama"], ano: 2012, classificacao: "PG-13", duracao: 164, popularidade: "popular", spoilerSensivel: false, sinopse: "Oito anos depois, Batman volta à ativa para enfrentar o terrorista Bane que ameaça Gotham." },
  { titulo: "Tenet", generos: ["Ação", "Ficção Científica", "Suspense"], ano: 2020, classificacao: "PG-13", duracao: 150, popularidade: "popular", spoilerSensivel: true, sinopse: "Um agente secreto precisa manipular o fluxo do tempo para evitar uma catástrofe mundial." },
  { titulo: "John Wick 4: Baba Yaga", generos: ["Ação", "Suspense"], ano: 2023, classificacao: "16+", duracao: 169, popularidade: "popular", spoilerSensivel: false, sinopse: "John Wick enfrenta a Alta Cúpula em uma luta pela própria liberdade ao redor do mundo." },
  { titulo: "Missão: Impossível - Acerto de Contas Parte Um", generos: ["Ação", "Aventura", "Suspense"], ano: 2023, classificacao: "PG-13", duracao: 163, popularidade: "popular", spoilerSensivel: false, sinopse: "Ethan Hunt precisa encontrar uma arma de inteligência artificial perigosa antes que caia em mãos erradas." },
  { titulo: "Missão: Impossível - O Acerto Final", generos: ["Ação", "Aventura", "Suspense"], ano: 2025, classificacao: "PG-13", duracao: 169, popularidade: "popular", spoilerSensivel: false, sinopse: "Ethan Hunt e sua equipe correm contra o tempo para impedir uma inteligência artificial fora de controle." },
  { titulo: "Velozes e Furiosos 10", generos: ["Ação", "Aventura"], ano: 2023, classificacao: "PG-13", duracao: 141, popularidade: "popular", spoilerSensivel: false, sinopse: "Dominic Toretto e sua família são perseguidos por um vilão que deseja vingança por eventos do passado." },
  { titulo: "Era Uma Vez em Hollywood", generos: ["Comédia", "Drama"], ano: 2019, classificacao: "18+", duracao: 161, popularidade: "cult", spoilerSensivel: false, sinopse: "Um ator em declínio e seu dublê tentam se adaptar à Hollywood de 1969, enquanto a cidade vive uma grande tensão." },
  { titulo: "O Irlandês", generos: ["Drama", "Suspense"], ano: 2019, classificacao: "18+", duracao: 209, popularidade: "cult", spoilerSensivel: false, sinopse: "Um ex-sindicalista relembra décadas de crimes a serviço da máfia e sua ligação com o líder sindical Jimmy Hoffa." },
  { titulo: "Assassinos da Lua das Flores", generos: ["Drama", "Suspense"], ano: 2023, classificacao: "16+", duracao: 206, popularidade: "cult", spoilerSensivel: false, sinopse: "Nos anos 1920, uma série de assassinatos atinge a tribo Osage em Oklahoma após a descoberta de petróleo em suas terras." },
  { titulo: "Babilônia", generos: ["Comédia", "Drama"], ano: 2022, classificacao: "18+", duracao: 189, popularidade: "cult", spoilerSensivel: false, sinopse: "A ascensão e queda de artistas em Hollywood na transição do cinema mudo para o falado." },
  { titulo: "Elvis", generos: ["Drama"], ano: 2022, classificacao: "PG-13", duracao: 159, popularidade: "popular", spoilerSensivel: false, sinopse: "A trajetória de Elvis Presley, do início da carreira à fama mundial, contada pelo ponto de vista de seu empresário." },
  { titulo: "Cavalo de Guerra", generos: ["Drama", "Aventura"], ano: 2011, classificacao: "PG-13", duracao: 146, popularidade: "popular", spoilerSensivel: false, sinopse: "Um cavalo é vendido para o exército durante a Primeira Guerra, e seu jovem dono tenta reencontrá-lo." },
  { titulo: "Lincoln", generos: ["Drama"], ano: 2012, classificacao: "PG-13", duracao: 150, popularidade: "cult", spoilerSensivel: false, sinopse: "Nos meses finais da Guerra Civil, o presidente Abraham Lincoln luta para aprovar a emenda que abole a escravidão." },
  { titulo: "Os Oito Odiados", generos: ["Suspense", "Drama"], ano: 2015, classificacao: "18+", duracao: 168, popularidade: "cult", spoilerSensivel: false, sinopse: "Presos por uma nevasca em uma cabana, oito desconhecidos escondem segredos que podem custar suas vidas." },
  { titulo: "Doutor Sono", generos: ["Terror", "Suspense", "Drama"], ano: 2019, classificacao: "16+", duracao: 152, popularidade: "popular", spoilerSensivel: false, sinopse: "Décadas depois dos eventos do hotel, Danny Torrance protege uma menina com poderes de um grupo sobrenatural." },
  { titulo: "It: Capítulo Dois", generos: ["Terror", "Suspense", "Drama"], ano: 2019, classificacao: "16+", duracao: 169, popularidade: "popular", spoilerSensivel: false, sinopse: "Vinte e sete anos depois, os amigos do Clube dos Perdedores voltam à cidade para enfrentar de novo a criatura." },
  { titulo: "Amor, Sublime Amor (2021)", generos: ["Romance", "Drama"], ano: 2021, classificacao: "PG-13", duracao: 156, popularidade: "popular", spoilerSensivel: false, sinopse: "Um amor nasce entre jovens de duas gangues rivais nas ruas de Nova York dos anos 1950." },
  { titulo: "Funny People", generos: ["Comédia", "Drama"], ano: 2009, classificacao: "16+", duracao: 146, popularidade: "cult", spoilerSensivel: false, sinopse: "Um comediante famoso diagnosticado com uma doença grave contrata um jovem iniciante como assistente e redescobre a amizade." },
  { titulo: "Homem de Aço", generos: ["Ação", "Ficção Científica", "Aventura"], ano: 2013, classificacao: "PG-13", duracao: 143, popularidade: "popular", spoilerSensivel: false, sinopse: "Clark Kent descobre suas origens e precisa defender a Terra de um general kryptoniano." },
  { titulo: "Eternos", generos: ["Ação", "Ficção Científica", "Aventura", "Fantasia"], ano: 2021, classificacao: "PG-13", duracao: 156, popularidade: "popular", spoilerSensivel: false, sinopse: "Seres imortais que protegem a humanidade há milênios voltam a se reunir para enfrentar uma antiga ameaça." },
  { titulo: "Flash", generos: ["Ação", "Ficção Científica", "Aventura"], ano: 2023, classificacao: "PG-13", duracao: 144, popularidade: "popular", spoilerSensivel: false, sinopse: "Barry Allen volta no tempo para salvar a mãe e acaba mudando o rumo do multiverso." },
  { titulo: "Aquaman", generos: ["Ação", "Aventura", "Fantasia"], ano: 2018, classificacao: "PG-13", duracao: 143, popularidade: "popular", spoilerSensivel: false, sinopse: "Arthur Curry precisa assumir o trono de Atlântida para impedir que seu meio-irmão declare guerra à superfície." },
  { titulo: "Indiana Jones e a Relíquia do Destino", generos: ["Ação", "Aventura"], ano: 2023, classificacao: "PG-13", duracao: 154, popularidade: "popular", spoilerSensivel: false, sinopse: "Indiana Jones, já idoso, parte para sua última aventura em busca de um artefato capaz de alterar o tempo." },
  { titulo: "Gladiador II", generos: ["Ação", "Aventura", "Drama"], ano: 2024, classificacao: "16+", duracao: 148, popularidade: "popular", spoilerSensivel: false, sinopse: "Anos depois de Maximus, um jovem é levado para o Coliseu e luta para enfrentar os governantes de Roma." },
  { titulo: "Napoleão", generos: ["Drama", "Ação", "Aventura"], ano: 2023, classificacao: "16+", duracao: 158, popularidade: "popular", spoilerSensivel: false, sinopse: "A ascensão e queda de Napoleão Bonaparte e sua relação turbulenta com Josefina." },
  { titulo: "Furiosa: Uma Saga Mad Max", generos: ["Ação", "Aventura", "Ficção Científica"], ano: 2024, classificacao: "16+", duracao: 148, popularidade: "popular", spoilerSensivel: false, sinopse: "A jovem Furiosa é sequestrada e luta para voltar para casa em meio ao caos do deserto." },
  { titulo: "Planeta dos Macacos: O Reinado", generos: ["Ficção Científica", "Aventura", "Ação"], ano: 2024, classificacao: "PG-13", duracao: 145, popularidade: "popular", spoilerSensivel: false, sinopse: "Muitas gerações depois de César, um jovem macaco parte em uma jornada que redefine o futuro de macacos e humanos." },
  { titulo: "A Substância", generos: ["Terror", "Ficção Científica", "Drama"], ano: 2024, classificacao: "18+", duracao: 141, popularidade: "cult", spoilerSensivel: true, sinopse: "Uma atriz em declínio usa uma substância misteriosa que cria uma versão mais jovem e perfeita de si mesma." },
  { titulo: "O Brutalista", generos: ["Drama"], ano: 2024, classificacao: "16+", duracao: 215, popularidade: "cult", spoilerSensivel: false, sinopse: "Um arquiteto judeu húngaro emigra para os Estados Unidos após a guerra e recebe a chance de construir uma obra monumental." },
  { titulo: "Demon Slayer: Castelo Infinito", generos: ["Animação", "Ação", "Fantasia", "Aventura"], ano: 2025, classificacao: "16+", duracao: 155, popularidade: "popular", spoilerSensivel: false, sinopse: "Tanjiro e os caçadores de demônios são levados para o Castelo Infinito, onde começa uma batalha decisiva." },
  { titulo: "F1: O Filme", generos: ["Ação", "Drama"], ano: 2025, classificacao: "PG-13", duracao: 155, popularidade: "popular", spoilerSensivel: false, sinopse: "Um piloto veterano volta às pistas para ajudar uma equipe em dificuldades ao lado de um jovem talento." },
  { titulo: "Uma Batalha Após a Outra", generos: ["Ação", "Comédia", "Drama", "Suspense"], ano: 2025, classificacao: "16+", duracao: 162, popularidade: "popular", spoilerSensivel: false, sinopse: "Um ex-revolucionário sai da vida clandestina para resgatar a filha quando seu antigo inimigo reaparece." },
  { titulo: "Frankenstein", generos: ["Terror", "Drama", "Fantasia", "Ficção Científica"], ano: 2025, classificacao: "16+", duracao: 149, popularidade: "popular", spoilerSensivel: false, sinopse: "Um cientista obcecado dá vida a uma criatura e precisa lidar com as consequências da própria ambição." },

  // --- Cinema brasileiro ---
  { titulo: "Carandiru", generos: ["Drama"], ano: 2003, classificacao: "18+", duracao: 146, popularidade: "popular", spoilerSensivel: false, sinopse: "Um médico entra na maior penitenciária da América Latina e conhece as histórias dos detentos até o massacre de 1992." },
  { titulo: "Marighella", generos: ["Drama", "Ação", "Suspense"], ano: 2019, classificacao: "16+", duracao: 155, popularidade: "cult", spoilerSensivel: false, sinopse: "Em 1969, Carlos Marighella lidera a luta armada contra o regime militar brasileiro." },
  { titulo: "Aquarius", generos: ["Drama"], ano: 2016, classificacao: "18+", duracao: 142, popularidade: "cult", spoilerSensivel: false, sinopse: "Uma crítica musical aposentada se recusa a vender seu apartamento para uma construtora que quer demolir o prédio." },
];

// ---------------------------------------------------------
// Estado do painel de personalização
// ---------------------------------------------------------
const estado = {
  epoca: "qualquer",
  duracao: "qualquer",
  popularidade: "qualquer",
};

// ---------------------------------------------------------
// Referências de elementos
// ---------------------------------------------------------
const ticket = document.getElementById("resultado");
const elTitulo = document.getElementById("filmeTitulo");
const elMeta = document.getElementById("filmeMeta");
const elDesc = document.getElementById("filmeDesc");
const elEyebrow = document.querySelector(".ticket__eyebrow");
const btnSortear = document.getElementById("btnSortear");
const checkboxSemSpoiler = document.getElementById("semSpoiler");

// Configura os grupos de botão de seleção única (época, duração, popularidade)
function configurarGrupoUnico(idGrupo, chaveEstado) {
  const grupo = document.getElementById(idGrupo);
  const botoes = grupo.querySelectorAll(".opcao-botao");
  botoes.forEach((botao) => {
    botao.addEventListener("click", () => {
      botoes.forEach((b) => b.classList.remove("is-ativa"));
      botao.classList.add("is-ativa");
      estado[chaveEstado] = botao.dataset.valor;
    });
  });
}

configurarGrupoUnico("grupoEpoca", "epoca");
configurarGrupoUnico("grupoDuracao", "duracao");
configurarGrupoUnico("grupoPopularidade", "popularidade");

// ---------------------------------------------------------
// Leitura das preferências marcadas em checkboxes
// ---------------------------------------------------------
function lerValoresMarcados(idGrupo) {
  const grupo = document.getElementById(idGrupo);
  return Array.from(grupo.querySelectorAll("input[type='checkbox']:checked")).map((i) => i.value);
}

function filmeCombinaComEpoca(filme, epoca) {
  if (epoca === "qualquer") return true;
  if (epoca === "classico") return filme.ano < 1990;
  if (epoca === "moderno") return filme.ano >= 1990 && filme.ano <= 2009;
  if (epoca === "recente") return filme.ano >= 2010;
  return true;
}

function filmeCombinaComDuracao(filme, duracao) {
  if (duracao === "qualquer") return true;
  if (duracao === "curta") return filme.duracao <= 90;
  if (duracao === "media") return filme.duracao > 90 && filme.duracao <= 140;
  if (duracao === "longa") return filme.duracao > 140;
  return true;
}

// ---------------------------------------------------------
// Filtro principal
// ---------------------------------------------------------
function filtrarFilmes() {
  const generosSelecionados = lerValoresMarcados("grupoGeneros");
  const classificacoesSelecionadas = lerValoresMarcados("grupoClassificacao");
  const evitarSpoiler = checkboxSemSpoiler.checked;

  return FILMES.filter((filme) => {
    const combinaGenero =
      generosSelecionados.length === 0 ||
      filme.generos.some((g) => generosSelecionados.includes(g));

    const combinaClassificacao =
      classificacoesSelecionadas.length === 0 ||
      classificacoesSelecionadas.includes(filme.classificacao);

    const combinaEpoca = filmeCombinaComEpoca(filme, estado.epoca);
    const combinaDuracao = filmeCombinaComDuracao(filme, estado.duracao);
    const combinaPopularidade =
      estado.popularidade === "qualquer" || filme.popularidade === estado.popularidade;
    const combinaSpoiler = !evitarSpoiler || !filme.spoilerSensivel;

    return (
      combinaGenero &&
      combinaClassificacao &&
      combinaEpoca &&
      combinaDuracao &&
      combinaPopularidade &&
      combinaSpoiler
    );
  });
}

// ---------------------------------------------------------
// Renderização do resultado
// ---------------------------------------------------------
function mostrarFilme(filme) {
  elEyebrow.textContent = "Sua sessão está pronta";
  elTitulo.textContent = filme.titulo;
  elMeta.textContent = `${filme.generos.join(", ")} — ${filme.ano} — ${filme.classificacao} — ${filme.duracao} min`;
  elDesc.textContent = filme.sinopse;
  dispararAnimacao();
}

function mostrarMensagemVazia() {
  elEyebrow.textContent = "Nenhuma sessão encontrada";
  elTitulo.textContent = "Nenhum filme combina com esses critérios";
  elMeta.textContent = "Tente liberar alguma preferência";
  elDesc.textContent = `Solte um gênero, mude a época ou a duração — a base tem ${FILMES.length} filmes esperando por um critério possível.`;
  dispararAnimacao();
}

function dispararAnimacao() {
  ticket.classList.remove("ticket--revelado");
  // força reflow para permitir repetir a animação em cliques seguidos
  void ticket.offsetWidth;
  ticket.classList.add("ticket--revelado");
}

// ---------------------------------------------------------
// Ação do botão
// ---------------------------------------------------------
btnSortear.addEventListener("click", () => {
  const candidatos = filtrarFilmes();
  if (candidatos.length === 0) {
    mostrarMensagemVazia();
    return;
  }
  const escolhido = candidatos[Math.floor(Math.random() * candidatos.length)];
  mostrarFilme(escolhido);
});